### PR TITLE
helm: do not render `PodSecurityPolicy` manifest on gke >= 1.25

### PR DESCRIPTION
**Pull request by ortuman**
Signed-off-by: Miguel Ángel Ortuño <ortuman@gmail.com>

#### What this PR does

`PodSecurityPolicy` resource will be completely removed from GKE in the future. This PR prevents it from being rendered on versions greater than 1.25.

#### Which issue(s) this PR fixes or relates to

Fixes N/A

#### Checklist

- [X] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by dimitarvdimitrov** [comment]
I'd err on the side of letting kubernetes reject the deprecated object. It's immediate feedback after running `helm install` or `helm upgrade` compared to silently the chart swallowing the incompatibility.

**Comment by dimitarvdimitrov** [comment]
actually I think we should [migrate to the pod admission controller](https://kubernetes.io/docs/tasks/configure-pod-container/migrate-from-psp/) instead of doing anything with the pod security policy

**Comment by dimitarvdimitrov** [comment]
after reading a bit, it turns out that this approach is actually the preferred one. I made another similar PR https://github.com/grafana/mimir/pull/2870

**Review by krajorama — COMMENTED** [review]
I've tested it with k8s 1.25, install was successful. However the role.yaml refers to the now non existent PSP which is a bit weird.

**Comment by dimitarvdimitrov** [comment]
@krajorama  did you try with the changes in https://github.com/grafana/mimir/pull/2870?

**Comment by krajorama** [comment]
> @krajorama did you try with the changes in #2870?

Testing

**Pull request closed without merging**
