### PR TITLE
Support resource requests and limits in metamonitoring grafana agent

### PR DESCRIPTION
**Pull request by PaulFarver**
#### What this PR does

Add `resources` blocks to the grafana agent containers created by the metamonitoring setup in the mimir-distributed chart

#### Checklist

- [ ] Tests updated.
- [x] Documentation added.
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [ ] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

### CODE REVIEW

**Review by dimitarvdimitrov — COMMENTED** [review]
have you tried setting this via the subchart `resources`? https://github.com/grafana/helm-charts/blob/main/charts/agent-operator/values.yaml#L70-L71

**Review by dimitarvdimitrov — APPROVED** [review]
the change looks reasonable. Have in mind that we'll be replacing the agent chart with alloy.

**Comment by PaulFarver** [comment]
Not really sure why the tests fail. Do the go unit tests render the helm chart?

**Comment by dimitarvdimitrov** [comment]
unfortunately it's a flaky test unrelated to your change (https://github.com/grafana/mimir/issues/8692). I retried the step and it should now pass

**Pull request merged**
