### PR TITLE
feat(helm): allow for deploying dashboards from mixin

### PR DESCRIPTION
**Pull request by DavidSpek**
#### What this PR does
This PR makes it possible to deploy the Grafana dashboards from the mixins as part of the helm chart. This is done by adding a symlink to the compiled dashboards (similar to the alert and rules). If enabled, a ConfigMap will be created for each dashboard.

#### Checklist

- [x] Tests updated
- [x] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by 56quarters** [comment]
> @56quarters Friendly ping to see if there is something I need to change for this.

I'm not a Helm expert so I'll add them to review

**Comment by DavidSpek** [comment]
@Logiraptor The label `grafana_dashboard` on the ConfigMaps will allow the sidecar that is deployed alongside Grafana to pick them up and add them to Grafana. The `k8s-sidecar-target-directory` annotation can be used to control which folder the dashboards are added to within Grafana. I believe the dashboard sidecar is deployed by default as part of the Grafana helm chart so it shouldn't need any special configuration for most users. This of course only works for a Grafana instance that is deployed in the same cluster as Mimir.

**Comment by DavidSpek** [comment]
I've deployed this yes. I initially tried just a single configmap with all dashboards which was too big. That is why I split it so a separate configmap is deployed for each dashboard. I'm guessing the test file doesn't split the different configmaps though and instead is a single file that has multiple configmaps in it.

**Comment by dimitarvdimitrov** [comment]
oh sorry, I was deceived by the single file in the rendered manifests. This change looks good to me 👍

**Review by Logiraptor — APPROVED** [review]
Tested this locally and it works great! 

Note some panels are blank unless you have the Mimir recording rules configured.

**Pull request merged**
