### PR TITLE
Add conditional read-after–write support to rules evaluation

### PR DESCRIPTION
**Pull request by pracucci**
#### What this PR does

This PR introduces conditional read-after-write (or strong read consistency) support for rule evaluations. This PR is based on https://github.com/grafana/mimir-prometheus/pull/587.

How it works:

- The Prometheus ruler evaluates whether each rule in a group is independent or not. A rule is independent if no other rule depends on it and it doesn't depend on any other in the group.
- The information whether a rule is independent or not is stored in the `RuleDetail` inside the context passed down to the ruler's query function.
- Mimir uses a custom query function. In this PR I've introduced a query function wrapper which reads the `RuleDetail` from the context and inject Mimir-specific read consistency requirement in the context.
- The Mimir-specific read consistency requirement is passed, via context and HTTP header (remote querier), through the network so that it gets correctly enforced in the ingesters.

> code easier in Prometheus

I will try to upstream the `mimir-prometheus` changes to Prometheus, in coordination with [Danny's PR](https://github.com/prometheus/prometheus/pull/12946) from which I've tool the dependency analysis code. However, I will not block on it.

#### Which issue(s) this PR fixes or relates to

N/A

#### Checklist

- [x] Tests updated.
- [ ] Documentation added.
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [ ] [`about-versioning.md`](/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

### CODE REVIEW

**Review by dimitarvdimitrov — APPROVED** [review]
nicely done, i really don't have any comments.

Would be nice if we can eventually improve `rule.Independant` to only apply where we need it (today it might significantly increase the number of read-after-write queries without needing that), but i suppose that's future work?

**Comment by pracucci** [comment]
> Would be nice if we can eventually improve rule.Independant to only apply where we need it (today it might significantly increase the number of read-after-write queries without needing that), but i suppose that's future work?

Yes, it's on my plate but I wanted to keep the scope of this PR smaller.

**Comment by pracucci** [comment]
@dimitarvdimitrov I've swapped the mimir-prometheus implementation with a simpler one ([here](https://github.com/grafana/mimir-prometheus/pull/587)) which doesn't include the concurrent rules evaluation support (given we don't need it in this PR). In the new mimir-prometheus implementation I've also exposed both "dependent rules" and "dependency rules" info, so in Mimir we can only enforce strong consistency on rules with dependencies.

I haven't update this PR description yet. Can you review the changes ([this commit](https://github.com/grafana/mimir/pull/7142/commits/6e5bae81e6af856b85e1a485b282f37053a72e91)) first, please?

**Review by dimitarvdimitrov — APPROVED** [review]
I had a closer look at the second revision and still LGTM

**Pull request merged**
