### PR TITLE
Feat/support aws sdk default credential provider chain

### LINKED ISSUE #5613: Support default authentication methods of the AWS SDK
#### Is your feature request related to a problem? Please describe.

In order to be able to use [cross-account IRSA with chained AssumeRole](https://docs.aws.amazon.com/eks/latest/userguide/cross-account-access.html), I need to possibility to set the AWS profile via AWS_PROFILE environment variable. I can inject the AWS configuration but it will not be picked up even if I set the correct profile name. I assume that the `aws_sdk_auth` field of the used thanos.io/objstore library is set to false by default and there is currently no way to set it to true.

#### Describe the solution you'd like

I would love to set the aws_sdk_auth field via configuration. For example:
````
mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          endpoint: s3.eu-central-1.amazonaws.com
          region: eu-central-1
          aws_sdk_auth: true
    blocks_storage:
      s3:
        bucket_name: s3bucket

````

#### Additional context

https://github.com/thanos-io/objstore#s3
https://github.com/thanos-io/objstore/blob/d0c43443ecda0d8cffbd4d215569a0dba9ba39ec/providers/s3/s3.go#L226
https://docs.aws.amazon.com/sdk-for-go/api/aws/session/

### PR DESCRIPTION
**Pull request by AljoschaP**
#### What this PR does
This PR allows to use the default credential provider chain of the AWS SDK. It is [already part](https://github.com/thanos-io/objstore/blob/d0c43443ecda0d8cffbd4d215569a0dba9ba39ec/README.md?plain=1#L190) of the used [thanos.io/objstore](https://github.com/thanos-io/objstore) and can now also be enabled for Mimir. The default credential provider chain allows the use of [e.g. role chaining using the `./aws/config`](https://github.com/grafana/mimir/discussions/5615) or other authentication methods which are not implemented in thanos.io/objstore or Mimir.

Example config:
````
mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          endpoint: s3.eu-central-1.amazonaws.com
          region: eu-central-1
          native_aws_auth_enabled: true
    blocks_storage:
      s3:
        bucket_name: mimir-bucket
````

#### Which issue(s) this PR fixes or relates to

Fixes #5613

#### Checklist

- [x] Tests updated
- [x] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by 56quarters** [comment]
Thanks for this PR! I'm confused about why it's necessary though (and why it was added to `thanos/objstore`). It seems like Minio does indeed support the same authentication methods that the AWS SDK does: 

https://github.com/minio/minio-go/tree/master/pkg/credentials

It seems like `objstore` [configures a few of them by default](https://github.com/thanos-io/objstore/blob/d0c43443ecda0d8cffbd4d215569a0dba9ba39ec/providers/s3/s3.go#L239-L250)

**Comment by AljoschaP** [comment]
I was also confused and during my research I found a lot of confusion in many issues/PRs and discussions around the topic. My guess is that there is a lot of reinventing the wheel again instead of relying on the default provider chain of the SDK and of course legacy code which doesn't support all of the countless ways how to authenticate against AWS. 

If I understand it correctly, the minio implementation had no way to use cross account role chaining when the `aws_sdk_auth` was introduced in the objstore [[1]](https://github.com/thanos-io/thanos/pull/4667)[[2]](https://github.com/thanos-io/thanos/pull/4667/files#r749424917). It seems that [it's supported](https://github.com/minio/minio-go/blob/master/pkg/credentials/assume_role.go)...maybe, but I need to try it out to be really sure. 

I can say that my use case (which was also the use case of the guy who introduced it in the objstore) is working properly now and I agree with him that relying on a consistent implementation from AWS is better than reimplementing it again and again and again. 

What do you think?

**Comment by 56quarters** [comment]
That makes sense to me. This is a much quicker way to let people use the auth logic they expect. My only suggestion is a different, slightly more descriptive name for the flag. What do you think about `native_aws_auth_discovery_enabled`?

**Comment by AljoschaP** [comment]
`native_aws_auth_enabled` maybe? to keep it short? 

Is it okay for you, if I fixup the existing commits? 😊

**Comment by 56quarters** [comment]
> `native_aws_auth_enabled` maybe? to keep it short?
> 
> Is it okay for you, if I fixup the existing commits? blush

Sure, sounds great. Thanks!

**Comment by 56quarters** [comment]
I think CI is failing because of whitespace. Can you run `make clean-white-noise` and push again? I can merge after that. Thanks!

**Review by 56quarters — APPROVED** [review]
LGTM, thanks!

**Comment by AljoschaP** [comment]
`make clean-white-noise` didn't change anything but I recreated it with `make reference-help` and there were some whitespace changes. Looks good now, when running the tests locally 🤞

**Pull request merged**
