### PR TITLE
Replace all blockquote admonitions with the shortcode

### PR DESCRIPTION
**Pull request by jdbaldry**
The [`admonition` shortcode](https://grafana.com/docs/writers-toolkit/write/shortcodes/#admonition) renders its content in a blockquote with consistent styling across the website.

I hope that this will also encourage future contributions to avoid blockquote notes and use the shortcode since it is common throughout the documentation.

### CODE REVIEW

**Comment by pstibrany** [comment]
> I hope that this will also encourage future contributions to avoid blockquote notes and use the shortcode since it is common throughout the documentation.

Blockquote syntax is much more memorable, can we please keep using it and let the tools handle the rendering?

**Comment by jdbaldry** [comment]
> Blockquote syntax is much more memorable (TIL that `admonition` term exists), can we please keep using it and let the tools handle the rendering?

Mm, I do agree that it's easier to remember blockquote syntax.

The website squad maintains the HTML template for the `admonition` shortcode and ensures that it has consistent styling, and also proper semantic tags, and attributes for accessibility. Conversely, blockquotes with bold text are just blockquotes in the HTML output and are inconsistently used throughout the documentation.

Example of different usage I've seen in Mimir documentation (also present for tips, warnings, and cautions):

- > **Note**: Capitalized first word
- > **NOTE**: Capitalized first word
- > **Note:** Capitalized first word
- > **NOTE:**: Capitalized first word
- > **Note**: lower first word
- > **NOTE**: lower first word
- > **Note:** lower first word
- > **NOTE:** lower first word

Unfortunately, there is no render hook in Hugo for blockquotes which means that the conversion cannot be done with Hugo alone -- https://github.com/gohugoio/hugo/issues/7876.

Of course we could introduce a transpilation step in Mimir but I think that would be more awkward than using the shortcode.

**Review by pstibrany — APPROVED** [review]
Unblocking.

**Comment by pstibrany** [comment]
> It would be great to merge this sooner rather than later because of the risk of conflicts with changes across so many files.

Feel free to merge this. I see that there's too much complexity to make blockquotes "just work", so let's use "admonition" for now.

**Comment by jdbaldry** [comment]
Thanks Peter, I agree.

I'm not authorized to merge PRs because I'm no longer a member of @grafana/mimir-maintainers. Would you mind doing the honors? :)

**Pull request merged**
