### PR TITLE
Merge release-2.9 into release-2.10

### PR DESCRIPTION
**Pull request by dimitarvdimitrov**

### CODE REVIEW

**Review by krajorama — APPROVED** [review]

**Review by pstibrany — APPROVED** [review]
Nice. 

Our merging script is not ready for doing merges to newer branch, so you'll need to do the merge manually, either on command line -- then pushing updated `release-2.10` branch will automatically close this PR, or by enabling merge commits.

**Comment by dimitarvdimitrov** [comment]
I enabled merge commits but keep getting the below error. If I choose a random other PR targetting main I can choose to proper-merge it, but not this one.

```
remote: error: This branch must not contain merge commits.
```

Screenshot 2023-12-13 at 10 34 34

Screenshot 2023-12-13 at 10 35 21

**Comment by pstibrany** [comment]
Oh right, we have protection for that on release-branches. You will need to temporarily disable that protection.

**Comment by dimitarvdimitrov** [comment]
i don't think this is a very viable workflow. TO do the merge commit I had to 
1. enable merge commits for the whole repository
2. allow administrators to override the branch protection rules (couldn't find the setting which forbids merge commits)

I reenabled them after the merge, but if we want to go this route of releases we need a new workflow. Until then doing the docs changes on main and backporting to multiple branches looks like a more reasonable approach to me

**Comment by pstibrany** [comment]
> couldn't find the setting which forbids merge commits

[It's this setting](https://github.com/grafana/mimir/settings/branch_protection_rules/28809885):

image

**Pull request merged**
