### PR TITLE
Use absolute path of template to decide if we need to remove it

### LINKED ISSUE #3591: alertmanager templating fail half of the time
#### Describe the bug
Templating fail half of the time.

#### To Reproduce

1. Start Mimir 2.4.0
`./mimir-linux-amd64 -target all,ruler,alertmanager --config.file=./demo.yaml`

2. Load a always on alerting rules
`mimirtool rules load alerts.yml`

3. Load a alertmanager configuration
`mimirtool alertmanager load alertmanager.yml sample.tmpl`

4. Use nc to see notifications
`nc -l 6527`

#### Expected behavior

No templating error reported in log for half of notifications
`level=error ts=2022-11-30T15:55:23.260898571Z caller=dispatch.go:352 component=MultiTenantAlertmanager user=anonymous component=dispatcher insight=true component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="opsgenie-P5/opsgenie[0]: notify retry canceled due to unrecoverable error after 1 attempts: templating error: template: :1:12: executing \"\" at <{{template \"sample\" .}}>: template \"sample\" not defined"`

#### Environment

- Infrastructure: laptop
- Deployment tool: none

#### Additional Context

While looking at data-alertmanager/anonymous/templates/ we can see the file sample.tmpl being deleted and recreated every 15s.
Might be related to https://github.com/cortexproject/cortex/issues/4888 ?

sample.tmpl
```
{{ define "sample" }}This is a sample static template{{ end }}
```

alertmanager.yml
```
global:
  # The API url is wrong on purpose as we want to test templating
  opsgenie_api_url: http://127.0.0.1:6527
  opsgenie_api_key: ABCD

route:
  receiver: opsgenie-P5
  repeat_interval: 30s
  group_interval: 1m
  group_by:
    - alertname

receivers:
- name: opsgenie-P5
  opsgenie_configs:
    - message: '{{ template "sample" . }}'
      priority: P5

templates:
- 'sample.tmpl'
```

alerts.yml
```
namespace: deadmanswitch
groups:
  - name: DeadManSwitch
    rules:
      - alert: DeadMansSwitch
        expr: vector(1)
        labels:
          severity: none
        annotations:
          description: >
            This is a DeadMansSwitch meant to ensure that
            the entire Alerting pipeline is functional.
          summary: Alerting DeadMansSwitch
```

demo.yaml
```
multitenancy_enabled: false

blocks_storage:
  backend: filesystem
  bucket_store:
    sync_dir: /tmp/mimir/tsdb-sync
  filesystem:
    dir: /tmp/mimir/data/tsdb
  tsdb:
    dir: /tmp/mimir/tsdb

compactor:
  data_dir: /tmp/mimir/compactor
  sharding_ring:
    kvstore:
      store: memberlist

distributor:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist

ingester:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist
    replication_factor: 1

ruler:
  alertmanager_url: http://127.0.0.1:8080/alertmanager

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/rules

server:
  http_listen_port: 8080
  log_level: info

store_gateway:
  sharding_ring:
    replication_factor: 1
```

### PR DESCRIPTION
**Pull request by vaxvms**
#### What this PR does

When alertmanager.data_dir is set to a relative path (as in default configuration), templates are deleted and recreated on a regular basis.
This PR fix the issue.

#### Which issue(s) this PR fixes or relates to

Fixes #3591

#### Checklist

- [x] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by aknuds1 — COMMENTED** [review]
Could this fix be accompanied by a test? I think that would be helpful in order to avoid a potential future regression :)

**Comment by vaxvms** [comment]
I'll need some guidance on how to write a test for this case.

I can trigger it in `multitenant_test.go:TestMultitenantAlertmanager_loadAndSyncConfigs` but only if user3Dir is a relative path. And user3Dir is an absolute path because of `multitenant_test.go:mockAlertmanagerConfig` using `t.TempDir()`

**Comment by pracucci** [comment]
> When alertmanager.data_dir is set to a relative path (as in default configuration), templates are deleted and recreated on a regular basis.

Why are they? I think I need more guidance on what the root cause is, to better understand the fix.

**Comment by aknuds1** [comment]
> Why are they? I think I need more guidance on what the root cause is, to better understand the fix.

I was also hoping a test would make it clearer how this bug is happening.

**Comment by vaxvms** [comment]
> > When alertmanager.data_dir is set to a relative path (as in default configuration), templates are deleted and recreated on a regular basis.
> 
> Why are they? I think I need more guidance on what the root cause is, to better understand the fix.

A list of file template all file templates is built at https://github.com/grafana/mimir/blob/main/pkg/alertmanager/multitenant.go#L638 

Then, at https://github.com/grafana/mimir/blob/main/pkg/alertmanager/multitenant.go#L649 they are removed from the list if they are still relevant (ie, in the received configuration). 

But at theses two steps, they aren't built in the same way :

- by joining configuration parameter with filename at the first step. If configuration is a relative path, we end up with a relative path
- by using `safeTemplateFilepath` function at the second step. This function always return an absolute path (see https://github.com/grafana/mimir/blob/main/pkg/alertmanager/multitenant.go#L1141 )

My PR built the two filenames the same way, fixing the bug.

**Comment by vaxvms** [comment]
> > Why are they? I think I need more guidance on what the root cause is, to better understand the fix.
> 
> I was also hoping a test would make it clearer how this bug is happening.

I've added a testcase in the PR

**Review by aknuds1 — CHANGES_REQUESTED** [review]
Thanks, this looks good as I can understand why you would need to make this fix (to mirror line 643) in light of your test.

Please review my language related suggestions :)

**Comment by vaxvms** [comment]
Thanks for your suggestions :) Here they are.

**Review by aknuds1 — APPROVED** [review]
LGTM, nice fix!

**Pull request merged**
