### PR TITLE
Introduce TENANT_LIMIT as a possible ingester error cause

### PR DESCRIPTION
**Pull request by duricanikolic**
#### What this PR does
This PR enriches the set of possible values of `mimirpb.ErrorCause` by adding one additional value, `TENANT_LIMIT`. The updated definition of the proto message is:
```
enum ErrorCause {
  INVALID = 0;
  REPLICAS_DID_NOT_MATCH = 1;
  TOO_MANY_CLUSTERS = 2;
  BAD_DATA = 3;
  INGESTION_RATE_LIMITED = 4;
  REQUEST_RATE_LIMITED = 5;
  INSTANCE_LIMIT = 6;
  TENANT_LIMIT = 7;
  SERVICE_UNAVAILABLE = 8;
  TSDB_UNAVAILABLE = 9;
}
```
Errors of type `ingesterError` having `mimirpb.TENANT_LIMIT` as `errorCause()` are mapped to `http.StatusBadRequest` (400) by `Ingester.handlePushError()`. Previously the `errorCause()` of these errors was `mimirpb.BAD_DATA`, and they were mapped to the same HTTP status. Therefore, this PR does not add any semantical change.

#### Which issue(s) this PR fixes or relates to

Part of https://github.com/grafana/mimir/issues/6008

#### Checklist

- [x] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by 56quarters** [comment]
I'm not sure `TENANT_LIMIT` makes sense semantically. Request rate and ingestion rate are also "tenant limits" but they're different error causes because they are mapped to different responses: rate limiting which can be retried instead of non-recoverable errors. I think the existing `BAD_DATA` is fine since it is a better fit for why a push request is being rejected: the data is bad and will never be valid.

**Comment by duricanikolic** [comment]
> I'm not sure `TENANT_LIMIT` makes sense semantically. Request rate and ingestion rate are also "tenant limits" but they're different error causes because they are mapped to different responses: rate limiting which can be retried instead of non-recoverable errors. I think the existing `BAD_DATA` is fine since it is a better fit for why a push request is being rejected: the data is bad and will never be valid.

Thank you for the feedback @56quarters. Does this answer make sense to you @replay?

If we all agree I will close this PR and leave the things as they are.

**Comment by replay** [comment]
> I'm not sure TENANT_LIMIT makes sense semantically. Request rate and ingestion rate are also "tenant limits" but they're different error causes because they are mapped to different responses: rate limiting which can be retried instead of non-recoverable errors. I think the existing BAD_DATA is fine since it is a better fit for why a push request is being rejected: the data is bad and will never be valid

I think this is making sense, but couldn't the same thing be said about `INSTANCE_LIMIT` then?
Currently the per-instance ingestion rate limit returns `INSTANCE_LIMIT`: https://github.com/grafana/mimir/blob/847212d348a9fee55fb84fbfb32843ecd7911a14/pkg/ingester/instance_limits.go#L25

**Comment by replay** [comment]
It also adds some useful comments:

https://github.com/grafana/mimir/pull/6431/files#diff-95a14e47177a04b392873b854e1908f68189d1c33c3e260efcafce7175c5009aR33-R40

**Comment by 56quarters** [comment]
> > I'm not sure TENANT_LIMIT makes sense semantically. Request rate and ingestion rate are also "tenant limits" but they're different error causes because they are mapped to different responses: rate limiting which can be retried instead of non-recoverable errors. I think the existing BAD_DATA is fine since it is a better fit for why a push request is being rejected: the data is bad and will never be valid
> 
> I think this is making sense, but couldn't the same thing be said about `INSTANCE_LIMIT` then? Currently the per-instance ingestion rate limit returns `INSTANCE_LIMIT`:
> 
> https://github.com/grafana/mimir/blob/847212d348a9fee55fb84fbfb32843ecd7911a14/pkg/ingester/instance_limits.go#L25

Instance limits are different from both tenant limits and validation errors. They aren't from invalid data and they aren't from a _user_ hitting a limit. They are from a pod hitting a limit due to a problem with the way Mimir is running or configured.

**Comment by 56quarters** [comment]
> Maybe we can just give it another name? I cannot think about a common name we could use for user/metric series/metadata limits. On the other hand, `TENANT_LIMIT` could be seen as a general tenant limit, while the others could be seen as special cases of tenant limits that need some different handling.

What's wrong with `BAD_DATA`? If a push request fails validation, `BAD_DATA` seems reasonable to me.

**Comment by replay** [comment]
Ok, I'm convinced. I'm sorry, I didn't intend to block you for so long with this Yuri.

**Comment by duricanikolic** [comment]
> Ok, I'm convinced. I'm sorry, I didn't intend to block you for so long with this Yuri.

No problem at all. My main goal is to improve the current situation and every comment, suggestion or doubt is very welcome. Thank you both.
I am going to push my next PR (the actual ingester error handling) tomorrow, and again every suggestion will be very well appreciated.

**Comment by duricanikolic** [comment]
After a discussion with @56quarters and @replay we have decided to close this PR without merging it.

**Pull request closed without merging**
