### PR TITLE
Merge release-2.9 branch into main

### PR DESCRIPTION
**Pull request by ying-jeanne**
This PR merges `release-2.9` branch into `main`.

Please merge this PR using a **merge commit** or by using `tools/release/merge-approved-pr-branch-to-main.sh` script.

### CODE REVIEW

**Comment by pstibrany** [comment]
Can you please run `make build-jsonnet-tests` again? There are new manifests on `main` that need to be regenerated too.

**Comment by pstibrany** [comment]
I've updated your PR non-description to something more ... descriptive :) And included request to merge with real Merge commit, so that we don't forget.

**Comment by ying-jeanne** [comment]
> I've updated your PR non-description to something more ... descriptive :) And included request to merge with real Merge commit, so that we don't forget.

thank you Peter, you are an angle reviewer.

**Comment by Footur** [comment]
Is the helm chart also updated by the pull request?

**Review by pstibrany — APPROVED** [review]

**Comment by pstibrany** [comment]
> Is the helm chart also updated by this pull request?

No, it's not. We update helm chart separately.

**Pull request merged**
