### PR TITLE
[Helm] Set unregister_on_shutdown to false for store-gateway

### LINKED ISSUE #4689: Helm: Should set `unregister_on_shutdown` to false for `store_gateway` by default.
In large deployments, updating the `store-gateway` can trip the https://grafana.com/docs/mimir/latest/operators-guide/mimir-runbooks/#mimirquerierhighrefetchrate alarm because of `store-gateway` ring resharding.

`unregister_on_shutdown` is false by default for the `ingester` `StatefulSet` since the identity/name persists and the ingester is never a `Deployment` when deployed via Helm so this is safe to do.

The `store-gateway` is also never a `Deployment` when deployed via Helm - there is only a `StatefulSet` template.

Therefore, it makes sense to also set `unregister_on_shutdown: false` for `store-gateway` also to speed up deployments.

I'll file the PR for this.

### PR DESCRIPTION
**Pull request by eamonryan**
#### What this PR does

In large deployments, updating the `store-gateway` can trip the https://grafana.com/docs/mimir/latest/operators-guide/mimir-runbooks/#mimirquerierhighrefetchrate alarm because of `store-gateway` ring resharding.

`unregister_on_shutdown` is false by default for the `ingester` `StatefulSet` since the identity/name persists and the `ingester` is never a `Deployment` when deployed via Helm so this is safe to do. See: https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/values.yaml#L269

The `store-gateway` is also never a `Deployment` when deployed via Helm - there is only a `StatefulSet` template.

Therefore, it makes sense to also set `unregister_on_shutdown: false` for `store-gateway` also to speed up deployments.

#### Which issue(s) this PR fixes or relates to

Fixes #4689 

#### Checklist

- [N/A] Tests updated
- [N/A] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by dimitarvdimitrov — APPROVED** [review]
Nice one! Thank you 🚀

**Comment by dimitarvdimitrov** [comment]
We have a tool which checks for drifts between the jsonnet and helm default configurations. I think unregistering from the ring is on by defualt for jsonnet, that's why the CI is failing in your PR. I see that is enabled for the store-gateways in jsonnet on when running multi-zone

https://github.com/grafana/mimir/blob/bd645f023d3a0cea11b4d5485c3b6874d083b067/operations/mimir/multi-zone.libsonnet#L201

I don't see a reason why it's not always enabled. Since this isn't in scope for your PR, you can disable the comparison of this particular config option between jsonnet and helm. To disable it, I think you should be able to add a line to this config (an empty key, just like `prefix` there) https://github.com/grafana/mimir/blob/3508a0b2ac8ed97642ef711e6b7dedcb54f324d2/operations/compare-helm-with-jsonnet/components/config/irrelevant-config.yaml#L42-L45


After merging your PR I can open one to do this in jsonnet as well

**Comment by eamonryan** [comment]
@dimitarvdimitrov Thanks for the information!

I made the change and the tests look all good now :)

**Review by krajorama — APPROVED** [review]
LGTM

**Pull request merged**
