### PR TITLE
Update dskit and use ring.DoUntilQuorumWithoutSuccessfulContextCancellation to reduce risk of memory leaks

### PR DESCRIPTION
**Pull request by charleskorn**
#### What this PR does

This PR updates dskit to the latest available version, which brings in https://github.com/grafana/dskit/pull/317, https://github.com/grafana/dskit/pull/318 and https://github.com/grafana/dskit/pull/319.

This PR also builds upon https://github.com/grafana/mimir/pull/5199 and https://github.com/grafana/dskit/pull/319 to reduce the likelihood of leaking `context.Context`s when querying ingesters.

#### Which issue(s) this PR fixes or relates to

(none)

#### Checklist

- [x] Tests updated
- [n/a] Documentation added
- [n/a] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by charleskorn** [comment]
Note to reviewers: I don't think this change needs a changelog entry given this is just making things more robust, rather than fixing an issue (the issue we know of was fixed in #5199). Happy to add one if you disagree.

**Review by pstibrany — APPROVED** [review]

**Review by pracucci — APPROVED** [review]
LGTM. I think we should revert the changes added in query-frontend and query-scheduler worker to always cancel the context. It shouldn't be required anymore, right?

**Comment by charleskorn** [comment]
> LGTM. I think we should revert the changes added in query-frontend and query-scheduler worker to always cancel the context. It shouldn't be required anymore, right?

I think it's worthwhile keeping them for the sake of consistency and to help guard against other similar leaks in the future. Other code paths that run a query (eg. hitting the Prometheus HTTP API) create a separate context for each request.

**Comment by charleskorn** [comment]
I'm going to merge this to unblock any future dskit upgrades, but happy to come back and address your comment @pracucci if you disagree with my response.

**Pull request merged**
