### PR TITLE
Add experimental kafkatool with 1 command: create-partitions

### PR DESCRIPTION
**Pull request by pracucci**
#### What this PR does

As part of our work on the experimental new Kafka-based architecture, I had a need to create more partitions. This looked the right time to introduce a new easy tool that we can use to operate Kafka. Over the time we can add the commands we need.

In this PR I'm adding `create-partitions` command, which I've successfully used to add more partitions:

```
$ /tmp/kafkatool --kafka-address=localhost:9092 create-partitions --topic=ingest --num-partitions=999

Number of partitions before creating additional partitions: 1
Created 999 additional partitions to topic ingest
Number of partitions after creating additional partitions: 1000
```

#### Which issue(s) this PR fixes or relates to

N/A

#### Checklist

- [ ] Tests updated.
- [ ] Documentation added.
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [ ] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

### CODE REVIEW

**Comment by dimitarvdimitrov** [comment]
have you tried using the kafka-tools scripts? There is already `kafka-topics.sh` which can create topics and partitions https://docs.confluent.io/kafka/operations-tools/kafka-tools.html#kafka-topics-sh

**Comment by pracucci** [comment]
> have you tried using the kafka-tools scripts? There is already `kafka-topics.sh` which can create topics and partitions https://docs.confluent.io/kafka/operations-tools/kafka-tools.html#kafka-topics-sh

I haven't. Switching the PR back to draft and, when I will have time, will investigate how annoying is setting up the scripts (a golang binary is very hard to beat... but I understand the benefit of having a bunch of commands at hand).

**Comment by rxacevedo** [comment]
How about [`kcl`](https://github.com/twmb/kcl)? It's written in Go (uses [`franz-go`](https://github.com/twmb/franz-go/)):

```
─> k exec -it warp -- bash -c 'kcl topic create test-topic --num-partitions 1'
NAME        MESSAGE
test-topic  OK

─> k exec -it warp -- bash -c 'kcl metadata --topics | head -n2'
NAME                                             ID                                PARTITIONS  REPLICAS
test-topic                                       37380000000000000000000000000000  1           1

─> k exec -it warp -- bash -c "kcl topic add-partitions -t test-topic "(seq 1 999 | tr '\n' ':')
test-topic  OK

─> k exec -it warp -- bash -c 'kcl metadata --topics | head -n2'
NAME                                             ID                                PARTITIONS  REPLICAS
test-topic                                       37380000000000000000000000000000  1000        1
```

**Comment by pracucci** [comment]
> Have you seen [kcl](https://github.com/twmb/kcl)? It's written in Go (uses [franz-go](https://github.com/twmb/franz-go/)):

I didn't know it, but looks very promising. I will give it a try!

**Comment by pstibrany** [comment]
> have you tried using the kafka-tools scripts? There is already `kafka-topics.sh` which can create topics and partitions https://docs.confluent.io/kafka/operations-tools/kafka-tools.html#kafka-topics-sh

I confirm that this works, I used it previously.

**Comment by pstibrany** [comment]
Note that `-ingest-storage.kafka.auto-create-topic-default-partitions` Mimir option can be used to automatically create topic with specified number of partitions.

**Comment by pstibrany** [comment]
Warpstream agents also have some Kafka client commands built-in:
```
$ docker run -t -i us-docker.pkg.dev/grafanalabs-dev/docker-warpstream-self-hosted-dev/warpstream-agent:main-5d8fed8 cli
Usage: warpstream kcmd sub-command [options]
Available sub-commands:
    alter-broker-config
    alter-topic-config
    api-versions
    broker-metadata
    commit-offsets
    console-consumer
    console-producer
    create-topic
    delete-all-topics-unsafe
    delete-topic
    describe-broker-configs
    describe-groups
    describe-log-dirs
    describe-topic-configs
    diagnose-connection
    fetch
    fetch-offsets
    list-groups
    list-offsets
    list-topics
    produce
    update
```

**Comment by pracucci** [comment]
> Note that `-ingest-storage.kafka.auto-create-topic-default-partitions` Mimir option can be used to automatically create topic with specified number of partitions.

Yes, sure. This tool was intended in case of emergency (which is the case I had).

**Pull request closed without merging**
