### PR TITLE
Update prometheus/client_golang to 1.17.0

### PR DESCRIPTION
**Pull request by bboreham**
#### What this PR does

Update prometheus/client_golang to 1.17.0, particularly to bring in a performance fix https://github.com/prometheus/client_golang/pull/1296.

Most changes are fixing spelling or punctuation in spelling, but there is also the addition of creation timestamps from https://github.com/prometheus/client_golang/pull/1313.

#### Checklist

- NA Tests updated
- NA Documentation added
- NA `CHANGELOG.md` updated - not user-visible.

### CODE REVIEW

**Comment by aknuds1** [comment]
I restarted the failing test, to see if it's a flake.

**Comment by krajorama** [comment]
duplicate of #6200

**Comment by aknuds1** [comment]
Rebase the PR and it should be good @bboreham :)

**Review by aknuds1 — APPROVED** [review]
LGTM, just needs rebasing to fix the failing test :)

**Pull request merged**
