### PR TITLE
Improve "rollout progress" dashboard

### PR DESCRIPTION
**Pull request by charleskorn**
#### What this PR does

This PR makes a number of small improvements to the "rollout progress" dashboard:

* it fixes the issue where the "unhealthy pods" panel could just show a number, rather than the name of the workload and the number of unhealthy pods if only one workload had unhealthy pods
* it adjusts the layout of the two left-most panels so that the "rollout progress" panel doesn't require scrolling
* it adjusts the order of the columns in the "pods count per version" panel so that the workload name is shown first
* it fixes the issue where some workloads aren't shown on the dashboard (now all Deployments and StatefulSets in the selected namespace are shown)
* it modifies the "rollout progress" panel to show the number of updated and ready pods for each workload (previously it just showed the number of updated pods)

This is what the dashboard looks like after all of these changes for a test cell at Grafana Labs:

Screenshot 2023-05-31 at 4 59 31 pm

#### Which issue(s) this PR fixes or relates to

(none)

#### Checklist

- [n/a] Tests updated
- [n/a] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by krajorama** [comment]
The code LGTM, although I'm no expert on dashboard json.
On the other hand the double bars in the rollout progress and seeing all deployment/statefulsets is more subjective question. I'd do a poll to be honest. Personally the double bars are too busy, hard on the eyes. And if someone has loki and tempo running in same namespace the whole thing could get very busy.

**Comment by charleskorn** [comment]
>On the other hand the double bars in the rollout progress and seeing all deployment/statefulsets is more subjective question. I'd do a poll to be honest. Personally the double bars are too busy, hard on the eyes. 

I'm very open to feedback / alternative suggestions here. 

I chose blue and green for the bars to avoid colours that suggest something is wrong (eg. red, orange or yellow), but I agree it can be difficult to read. I could try some different colours perhaps? Or split updated and healthy to separate panels, replacing the "unhealthy pods" panel?

> And if someone has loki and tempo running in same namespace the whole thing could get very busy.

Is this something we recommend or support?

**Comment by krajorama** [comment]
> > On the other hand the double bars in the rollout progress and seeing all deployment/statefulsets is more subjective question. I'd do a poll to be honest. Personally the double bars are too busy, hard on the eyes.
> 
> I'm very open to feedback / alternative suggestions here.
> 
> I chose blue and green for the bars to avoid colours that suggest something is wrong (eg. red, orange or yellow), but I agree it can be difficult to read. I could try some different colours perhaps? Or split updated and healthy to separate panels, replacing the "unhealthy pods" panel?

I kind of like the unhealthy pods panel, shows me exactly what its name suggests. Personally I don't need the extra bar for unhealthy anywhere. But again, that's just me. Maybe we should just make the change in our environment and get people's feedback.

> 
> > And if someone has loki and tempo running in same namespace the whole thing could get very busy.
> 
> Is this something we recommend or support?

That's a good question, I don't think we document this anywhere.
By the way , in "Pods count per version" we only show rows where the version has 'r.*', is that correct? Who is this dashboard for in that case? People should be using stable versions, those are not versioned that way.

**Comment by charleskorn** [comment]
> I kind of like the unhealthy pods panel, shows me exactly what its name suggests. Personally I don't need the extra bar for unhealthy anywhere. But again, that's just me. 

For me, showing the percentage of unhealthy pods puts the number of unhealthy pods in context - for example, seeing that there's five unhealthy queriers doesn't tell me if that's worthy of concern or not, but seeing if 10% or 80% of all queriers are unhealthy tells me if I need to worry about it.

> By the way , in "Pods count per version" we only show rows where the version has 'r.*', is that correct? Who is this dashboard for in that case? People should be using stable versions, those are not versioned that way.

Are you referring to [this override](https://github.com/grafana/mimir/pull/5113/files#diff-8f1a7f945f4b3af619ebb57f3a916a1f424359fc97d78f188488409b373023d7R1191-R1204) for columns that start with `r`? If so, that just seems to be a formatting override, the query still selects and shows all versions.

**Comment by flxbk** [comment]
The CHANGELOG has just been cut to prepare for the next Mimir release. Please rebase `main` and eventually move the CHANGELOG entry added / updated in this PR to the top of the CHANGELOG document. Thanks!

**Comment by krajorama** [comment]
> > I kind of like the unhealthy pods panel, shows me exactly what its name suggests. Personally I don't need the extra bar for unhealthy anywhere. But again, that's just me.
> 
> For me, showing the percentage of unhealthy pods puts the number of unhealthy pods in context - for example, seeing that there's five unhealthy queriers doesn't tell me if that's worthy of concern or not, but seeing if 10% or 80% of all queriers are unhealthy tells me if I need to worry about it.

I see. I'm not sure how easy it is to see with the bars combined. Possibly you could mention the percentage of failed pods in the unhealthy PODs part. So if 0% of pods are unhealthy then the component is not shown and if 20% failed, you'd list it as:
| component | 4 | 20% failed |
Anyway. As discussed IRL we could just try it out internally and get feedback. Please update with main, approving.

> 
> > By the way , in "Pods count per version" we only show rows where the version has 'r.*', is that correct? Who is this dashboard for in that case? People should be using stable versions, those are not versioned that way.
> 
> Are you referring to [this override](https://github.com/grafana/mimir/pull/5113/files#diff-8f1a7f945f4b3af619ebb57f3a916a1f424359fc97d78f188488409b373023d7R1191-R1204) for columns that start with `r`? If so, that just seems to be a formatting override, the query still selects and shows all versions.

Ah, misunderstood that override.

**Review by krajorama — APPROVED** [review]
LGTM, let's try it

**Pull request merged**
