### PR TITLE
Merge release 2.2 to main

### PR DESCRIPTION
**Pull request by colega**
#### What this PR does

Merges changes from release-2.2, with rc.1 version back to `main`.
This had quite a lot of conflicts on the docs side, but I think I managed to makse some sense of it.

#### Which issue(s) this PR fixes or relates to

Ref: https://github.com/grafana/mimir/issues/2241

#### Checklist

- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by colega** [comment]
Going to do it the other way tomorrow.

**Comment by colega** [comment]
The other way happens to bring the same commits:
https://github.com/grafana/mimir/compare/merge-release-2.2-to-main-the-other-way?expand=1

Marking this as draft because I'm going to merge it from CLI.

**Comment by pstibrany** [comment]
> The other way (branching from `main` and merging `release-2.2` there) happens to bring the same commits: https://github.com/grafana/mimir/compare/merge-release-2.2-to-main-the-other-way?expand=1

The commit may look the same but this branch has wrong merge parents: first parent being commit from `release-2.2` branch. "the other way" has correct order of parent commits, indicating merge into "main", not into "release-2.2". I would suggest to proceed with that branch instead.

**Comment by colega** [comment]
Closing in favor of https://github.com/grafana/mimir/pull/2375

**Pull request closed without merging**
