### PR TITLE
Rename mimirpb.WriteErrorDetails in mimirpb.ErrorDetails

### PR DESCRIPTION
**Pull request by duricanikolic**
#### What this PR does
This PR renames `mimirpb.WriteErrorDetails` proto message into `mimirpb.ErrorDetail`.

#### Which issue(s) this PR fixes or relates to

Part of https://github.com/grafana/mimir/issues/6008.

#### Checklist

- [x] Tests updated.
- [ ] Documentation added.
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [ ] [`about-versioning.md`](/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

### CODE REVIEW

**Review by bboreham — APPROVED** [review]
Seems a straight rename.  `WriteErrorDetails` was introduced relatively recently, in #6377

**Comment by colega** [comment]
Can you clarify here why we can be sure that this isn't used anywhere? (Flags, etc.?)

**Comment by duricanikolic** [comment]
> Can you clarify here why we can be sure that this isn't used anywhere? (Flags, etc.?)

This is something we recently introduced in mimir, with the idea to use `WriteErrorDetails` on ingester's write path, and then to add `ReadErrorDetails` to be used on ingester's read path. Both usages were intended to be internal, for transfering error detail info from server to client sides. I have realized that the only error detail that we need on both write and read path is the error cause (`enum mimirpb.ErrorCause`), so the options were:
- keep using `WriteErrorDetails` on both write and read path, or
- introduce `ReadErrorDetail` which will have the same structure as `WriteErrorDetail` and use that one, or
- rename `WriteErrorDetails` to `ErrorDetails` and use it on both write and read paths.

As I mentioned above, `mimirpb.WriteErrorDetails` was intended to be used internally, and was placed in the `mimirpb` package just because that way it could be accessed by all mimir components. The existence of the struct wasn't even documented in CHANGELOG.

**Comment by colega** [comment]
But, could there be somewhere (in our infrastructure, or in a customer's infrastructure) a setup that is already sending this model on the wire?

**Comment by duricanikolic** [comment]
> But, could there be somewhere (in our infrastructure, or in a customer's infrastructure) a setup that is already sending this model on the wire?

So far `mimirpb.WriteErrorDetails` is used in the following cases:
- in `Distributor.Push()` so that distributor server passes the error details to the distributor client. The only known caller of `Distributor.Push()` is batcher.go in backend-enterprise, and it doesn’t use `mimirpb.WriteErrorDetails`
- in `Distributor.PushWithMiddlewares()`, and this is used by the push handler, so the push handler, depending on the error detail, can chose to which HTTP status code the error will be mapped. Both distributor and push handler are in the distributor package, so they will be shipped together.
- in `Ingester.Push()`, to send error details from ingester server to ingester client. These error details are then propagated from the ingester client to the distributor. But this happens only when `-ingester.return-only-grpc-errors` is set to true. And currently this is the case only in `mimir-dev-11`.

Setting `-ingester.return-only-grpc-errors` to true, without previously setting `-server.report-grpc-codes-in-instrumentation-label-enabled` and `-ingester.client.report-grpc-codes-in-instrumentation-label-enabled` to true would make the evaluation rules fail, because gRPC codes would be mapped to the error label. The last 2 configuration are set to true only in our dev cells.

So, we do send this over network, but in the current settings it is not dangerous.

**Comment by colega** [comment]
Thank you. So we just need to mention it in the changelog where we defined the `-ingester.return-only-grpc-errors` flag, and make sure this is included in Mimir 2.11 to avoid making a breaking change between 2.11 and 2.12 :+1:

**Review by colega — APPROVED** [review]

**Pull request merged**
