### PR TITLE
Influx push handler

### PR DESCRIPTION
**Pull request by colega**
#### What this PR does

Adds an http handler that accepts writes in the Influx [Line protocol](https://docs.influxdata.com/influxdb/cloud/reference/syntax/line-protocol/). This code is brought from https://github.com/grafana/influx2cortex with some minor adjustments.

#### Which issue(s) this PR fixes or relates to

None yet, internal discussion.

#### Checklist

- [x] Tests updated
- [ ] End-to-end tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by colega** [comment]
The code here is easy (pending to add some e2e tests which would be straightforwards), it's more about the conversation about whether we want this to be achieved this way (i.e., having this code directly in Mimir).

IMO, this is the way we should go, given the simplicity of the implementation and maintenance.

**Comment by 56quarters** [comment]
I agree with Peter that using one approach for some protocols and another for other protocols is confusing.

FWIW, in GEM we use the following approach:
* The code for implementing each protocol lives in a separate repo, maintained by the query team.
* That code is added to GEM as a dependency.
* Each supported proxy is started within GEM as a module with its own corresponding target, e.g. `-target=graphite-write`.

I think this is a decent balance between ease of use for users and ease of maintenance for us.

**Comment by colega** [comment]
> I think this is a decent balance between ease of use for users and ease of maintenance for us.

Vendoring code doesn't simplify maintenance but only makes it more complicated, while end users don't really care if code comes from vendor/ or from pkg/

**Comment by 56quarters** [comment]
> > I think this is a decent balance between ease of use for users and ease of maintenance for us.
> 
> Vendoring code doesn't simplify maintenance but only makes it more complicated, while end users don't really care if code comes from vendor/ or from pkg/

My point was more that the query squad would maintain it and be able to iterate on it as they please, the code in Mimir would only be responsible for wiring up the configuration for it.

**Pull request closed without merging**
