### PR TITLE
Mixin: Add flexibility to slow queries component label

### PR DESCRIPTION
**Pull request by QuentinBisson**
#### What this PR does

This PR allows users to change the component label in loki logs as the name label is not always defined (e.g. for promtail users) as explained here https://github.com/grafana/mimir/issues/5558#issuecomment-2062501431

#### Which issue(s) this PR fixes or relates to

Helps fixing https://github.com/grafana/mimir/issues/5558 later

#### Checklist

- [ ] Tests updated.
- [ ] Documentation added.
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [ ] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

### CODE REVIEW

**Review by dimitarvdimitrov — COMMENTED** [review]
awesome! can you also update the docs to mention that `name` is no configurable? https://github.com/grafana/mimir/blob/460bb22789a5880e3c2f542e9bb84c81b84dafc6/docs/sources/mimir/manage/monitor-grafana-mimir/requirements.md#L102

**Comment by QuentinBisson** [comment]
Of course i'll do that on monday :)

**Comment by QuentinBisson** [comment]
It's one @dimitarvdimitrov

**Review by dimitarvdimitrov — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
