### PR TITLE
Helm: Support creation of HorizontalPodAutoscaler

### LINKED ISSUE #3430: Add support for HPA in mimir-distributed
#### Is your feature request related to a problem? Please describe.

I have been running Grafana Mimir in our infrastructure using the Helm chart and I'm not currently able to automatically scale mimir in response to changes in load on the servers.

#### Describe the solution you'd like

It would be very helpful if Horizontal Pod Autoscalers were supported natively in the mimir-distributed helm chart.

#### Describe alternatives you've considered

I've attempted to add this manually using custom manifests with the chart to create HPAs for each component (Distributor, Querier, etc.), however, this is not an optimal solution since the `replicas` field on each Deployment and StatefulSet cannot be removed with the current templating. When using a custom HPA with the helm chart, applying any changes to one of the Deployments/StatefulSets causes a scale down to the number specified by the `replicas` field, followed by a scale up once the HPA has updated the desired replicas. In production, this is not ideal since it will potentially terminate active pods and disrupt our cluster's monitoring. 

As of now, my best solution is to fork the chart and add templating to omit this field, but it would be nice if this could be officially supported.

### PR DESCRIPTION
**Pull request by jgutschon**
#### What this PR does

This adds a generic template for a HorizontalPodAutoscaler under `templates/lib/hpa.tpl` along with templating to generate HPAs for the following components:

- alertmanager
- compactor
- distributor
- ingester
- querier
- query-frontend
- query-scheduler
- store-gateway

The existing HPAs for the gateway and deprecated nginx pods have also been migrated to use this template. Notable changes resulting from this migration include that the `behavior` field may now be used, and the metrics target types have been changed to `type: Utilization` since these are scaling based on the percentage utilization of the metric. The requirements for using the `autoscaling/v2` API have also been changed to K8s 1.23+ instead of 1.25+ since this API version is [GA as of 1.23](https://kubernetes.io/blog/2021/12/07/kubernetes-1-23-release-announcement/#horizontalpodautoscaler-v2-graduates-to-ga).

When using this with zone-aware components, individual HPAs are created per zone, and the `hpa.minReplicas` value is used instead of `replicas` in the `zoneAwareReplicationMap` template to ensure an even spread of pods at the minimum level.

#### Which issue(s) this PR fixes or relates to

Fixes #3430 

#### Checklist

- [ ] Tests updated
- [x] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by TaylorMutch** [comment]
How would autoscaling the ingesters work with zone awareness enabled?

**Comment by jgutschon** [comment]
> How would autoscaling the ingesters work with zone awareness enabled?

An HPA will be created for each zone if zone-awareness is enabled and then it will just scale within that zone based on the `averageMemoryUtilization` and `averageCpuUtilization` values set on the HPA. I've used this templating in our own deployment of mimir successfully with some extra behavior settings to avoid pod thrashing. For the ingester specifically, I set the `scaleDown` policy to disabled and instead handle downsizing manually due to the steps outlined [here](https://grafana.com/docs/mimir/latest/operators-guide/run-production-environment/scaling-out/#scaling-down-ingesters-deployed-in-multiple-zones). It's still useful for us to have it able to scale up automatically however, so I've included here.

**Comment by TaylorMutch** [comment]
So just to confirm, if one of the statefulsets scales up by one, does it automatically scale up the other two (assuming 3 zones)? Otherwise you might have an imbalance

**Comment by jgutschon** [comment]
Since each zone would have its own HPA, they will only scale within the respective zone, so yes, it could become imbalanced. Realistically though, if one zone had to scale up due to high memory usage, the others would likely scale as well since the resource usage is almost the same across each zone. Either way, I didn't think this would be a problem since the docs just recommend balancing zones to ensure resource utilization is also balanced.

**Comment by TaylorMutch** [comment]
Likely true; makes sense

**Comment by Logiraptor** [comment]
@jgutschon Thanks for all this work! I've been out of office this week, so I've made a note to follow up when I'm back next week. I haven't finished completely reviewing / testing everything yet, but so far here are my thoughts in no particular order:

* Internally we autoscale queriers based on the query scheduler queue size, since adding queriers won't help if the work to do is not shardable. Of course, this complicates things because now you need to query Mimir's own metrics, which means they need to be stored somewhere, and ideally that's not Mimir itself so you don't have a cascading failure.
* I'm still a little nervous about autoscaling ingesters, specifically because automatically scaling down will lead to lost data by default. I would want to explicitly prevent downscaling somehow rather than relying on the users to configure it correctly. I think many users will see `autoscaling` and just flip all the booleans to true without reading deeper into it.
* I noticed some fields changed in the gateway autoscaling, this is a breaking change and I'm wondering if we can keep the old naming to avoid that?
* Thanks a ton for adding docs!
* Have you tested the migration from current state to autoscaling? I think depending on how it all works out sometimes you can end up scaling to 0 temporarily, which would be bad for ingesters of course.
* Depending on how shuffle sharding is configured, scaling up won't always make use of those extra replicas. This applies to several parts of the system, and I'm a little nervous about that edge case biting users over time. I wonder how we can avoid confusion here 🤔 

Also tagging @krajorama and @dimitarvdimitrov in case they have thoughts :)

**Comment by jgutschon** [comment]
Hi @Logiraptor, thanks for taking a look. I've reverted the naming for the gateway autoscaling fields and disabled the `scaleDown` policy for the ingester HPA. I've also added some of the scaling behavior settings that we have been using in our own custom deployment of mimir to prevent pod thrashing.

For the querier autoscaling, I understand that the Jsonnet autoscaling makes use of KEDA to scale based on this queue size as well as some other metrics, such as in this [template](https://github.com/grafana/mimir/blob/3d14b39c7fde2f10a38875460aecd18ce639d0dd/operations/mimir-tests/test-autoscaling-generated.yaml#L1766). I was tentatively planning to add support for KEDA ScaledObjects in a later PR if this one was accepted, but I figured this would be a good baseline for that and it would still be useful to have autoscaling based on the memory and/or CPU for now.

I've just tested migrating a little bit now and I'm seeing that it's scaling down to 1 replica momentarily after creating the HPA. As far as I understand, I think a new revision of the Deployment or StatefulSet needs to be created at the same time as the HPA, omitting the `replicas` field, and this behavior will be prevented but I'm not 100% sure. I'll investigate more and see if this can be avoided another way since changing the replicas won't trigger a new revision to be created.

**Comment by hajowieland** [comment]
Hy there, and thanks for your great work @jgutschon .
Any updates when this will be merged @krajorama @Logiraptor ?

**Comment by pracucci** [comment]
@jgutschon @krajorama Hi! I'm checking draft PRs. What's the state of this PR? Should we move forward or close it?

**Comment by jgutschon** [comment]
Hi @pracucci, taking another look at this now, it seems that there are some k8s docs on this specific topic: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#migrating-deployments-and-statefulsets-to-horizontal-autoscaling

I've just tried the steps in the client-side option after enabling the HPA and it worked successfully without scaling down the pods. 

Worth noting here as well that I had originally solved this with ArgoCD by ignoring the `replicas` field entirely with the following config on the Application manifest, however this isn't a generalized solution for Helm users:

```
ignoreDifferences:
  - group: apps
    kind: Deployment
    managedFieldsManagers:
      - kube-controller-manager
```

I'll see if I have some time in the next few days to update the docs with the extra migration steps and address some of @Logiraptor's points, would be happy if this could still be merged.

**Comment by dimitarvdimitrov** [comment]
worth noting that there's another PR attempting to introduce HPA into the helm chart #4687. That uses KEDA and the same queries for autoscaling that the jsonnet library uses. I am not sure if @DavidSpek is still available to work on it.

I think it will be easier to maintain and provide support for if all the deployment tooling deployed similar autoscaling methods.

As @Logiraptor mentioned, autoscaling of different components can be very different. We're adding autoscaling of more components to jsonnet and internally testing it out extensively. Perhaps starting with some already tested components like the distributor, querier, query-frontend is a good starting point.

Regarding migrations: I think we might have some (internal?) docs for how to do the migration to KEDA autoscaling that we can share

**Comment by pracucci** [comment]
> worth noting that there's another PR attempting to introduce HPA into the helm chart https://github.com/grafana/mimir/pull/4687

I'm closing this PR in favour of #4687 which looks has received more progress recently, but please feel free to re-open this PR if work gets resumed.

**Pull request closed without merging**
