### PR TITLE
Upgrade golangci-lint to v1.52.2

### PR DESCRIPTION
**Pull request by charleskorn**
#### What this PR does

This PR upgrades `golangci-lint` to v1.52.2 and fixes all new linting warnings, primarily from the upgraded version of `revive`.

Some warnings are false positives (see https://github.com/mgechev/revive/issues/386) and have been ignored. The new `if-return` rule from `revive` enabled by default seemed unnecessary and has been disabled.

ℹ️ This PR will require a maintainer with permission to push the build image to Docker Hub to build and push the build image to Docker Hub and then update the image tag in the `Makefile` before merging (see [these instructions](https://github.com/grafana/mimir/blob/main/docs/internal/contributing/how-to-upgrade-golang-version.md)).

#### Which issue(s) this PR fixes or relates to

(none)

#### Checklist

- [n/a] Tests updated
- [n/a] Documentation added
- [n/a] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by aknuds1** [comment]
I'm pushing a new build, and will update the PR as you request :)

**Review by aknuds1 — APPROVED** [review]
LGTM - I <3 linters

**Review by pracucci — APPROVED** [review]
LGTM. @aknuds1 can you merge the PR once you've done publishing the new build image? I have another big refactoring PR lining up and I don't want to deal with such conflicts. Thanks!

**Comment by aknuds1** [comment]
@pracucci I will fix the conflicts and merge.

**Comment by pracucci** [comment]
@aknuds1 About this linter error:
```
func NewFetcherMetrics(reg prometheus.Registerer, syncedExtraLabels, modifiedExtraLabels [][]string) *FetcherMetrics {
```

You can just make the linter happy. I will take care of removing that dead code in a follow up PR.

**Pull request merged**
