### PR TITLE
[release-2.9] Backport chore(deps): update golang docker tag to v1.21.3  and x/net to v0.17 (#6325)

### PR DESCRIPTION
**Pull request by lamida**
#### What this PR does

Manual backport of #6325. Update golang docker tag to v1.21.3 (cherry picked from commit ed62c6eb7ee8efceda0081713e668265505ebe6e).

#### Checklist

- [na] Tests updated
- [na] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by duricanikolic — APPROVED** [review]
LGTM

**Review by pstibrany — CHANGES_REQUESTED** [review]
We don't want to update to Go 1.21.3 on this branch.

**Comment by pstibrany** [comment]
This branch already has patched Go version, brought by https://github.com/grafana/mimir/pull/6354.

**Comment by lamida** [comment]
Oh, my bad. I missed that PR. I will close this then.

**Pull request closed without merging**
