### PR TITLE
Grpc s2 compression

### LINKED ISSUE #8522: zstd compression support between distributors and ingesters
#### Is your feature request related to a problem? Please describe.
Are there plans for zstd support between distributors and ingesters using the `grpc_compression` flag? 

Enabling zstd compression would help significantly reduce the amount of cross-AZ traffic our org pays for running Mimir. gzip gets some wins, at the expense of CPU.

Now that there is a pure Go zstd implementation, are there any major blockers for introducing it to Mimir?

#### Describe the solution you'd like
Support for `zstd` when using the `grpc_compression`.

### PR DESCRIPTION
**Pull request by deniszh**
#### What this PR does

Adding GRPC S2 compression for better cross AZ traffic compression, with same CPU and better memory than Snappy.

#### Which issue(s) this PR fixes or relates to

Fixes #8522 

#### Checklist

- [ ] Tests updated.
- [ ] Documentation added.
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [ ] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

### CODE REVIEW

**Comment by aknuds1** [comment]
I'll review this when I have some time :)

**Comment by aknuds1** [comment]
Taking a look.

**Comment by aknuds1** [comment]
@deniszh I've drafted an alternative [PR](https://github.com/grafana/mimir/pull/9322) that uses the custom gRPC compressor support in dskit (approved, but not yet merged). WDYT about this approach?

**Comment by deniszh** [comment]
@aknuds1 : Looks good, thanks!

**Comment by deniszh** [comment]
Closed in the favour of #9292

**Pull request closed without merging**
