### PR TITLE
Chore: refactor ruler tests initialization

### PR DESCRIPTION
**Pull request by pracucci**
#### What this PR does
This PR does a refactoring in ruler tests, follow up a feedback received [here](https://github.com/grafana/mimir/pull/3088#discussion_r983560600) and [here](https://github.com/grafana/mimir/pull/3088#discussion_r983569287).

The diff is quite difficult to read, so suggest to review it commit-by-commit which should be way easier:
- [Removed ruleLimits from pkg/ruler and use the mock from pkg/util/validation instead](https://github.com/grafana/mimir/commit/21080f83f8116926f52205d2f0d90311bd522762) 
- [Removed buildAndStartRuler() in favour of buildRuler(..., withStart())](https://github.com/grafana/mimir/commit/26a2444d06ab1e2cc022046d1b178ef5be3bc039)
- [Renamed buildRuler() to prepareRuler()](https://github.com/grafana/mimir/commit/a6881c6f70cbd0c1852dcd5606ab55ce43c98294)
- [Moved default limits initialization out of testSetup()](https://github.com/grafana/mimir/commit/2ed24dd3e7751dfe295d03584ee0e065328b76e7)
- [Renamed newManager() to prepareRulerManager(), removed testSetup() and moved testSetup() logic partially to prepareRulerManager() and partially to prepareOptions](https://github.com/grafana/mimir/commit/a3b8c2146d9bd21e9dd054499ec82ac8d36608b9) 
- [Added withRulerAddrMap() option](https://github.com/grafana/mimir/pull/3090/commits/0cb36c5250a2df6318b3c24f5fcb8fb6fa4053c3)
- [Added withLimits() prepare option](https://github.com/grafana/mimir/pull/3090/commits/9d624803cd860fec2325c9e52a617de879ea402d)

#### Which issue(s) this PR fixes or relates to

N/A

#### Checklist

- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by dimitarvdimitrov — APPROVED** [review]
LGTM, thanks for addressing my feedback

**Review by jhesketh — APPROVED** [review]
lgtm.

I ran a coverage check before/after this change and these were the only changes (first line before patch, second line after):

```
ok  	github.com/grafana/mimir/pkg/compactor	92.946s	coverage: 84.9% of statements
ok  	github.com/grafana/mimir/pkg/compactor	76.108s	coverage: 85.0% of statements
```

```
ok  	github.com/grafana/mimir/pkg/ingester	137.764s	coverage: 86.3% of statements
ok  	github.com/grafana/mimir/pkg/ingester	107.014s	coverage: 86.2% of statements
```

```
ok  	github.com/grafana/mimir/pkg/mimirpb	0.128s	coverage: 13.0% of statements
ok  	github.com/grafana/mimir/pkg/mimirpb	0.123s	coverage: 12.2% of statements
```

```
ok  	github.com/grafana/mimir/pkg/ruler	12.461s	coverage: 35.2% of statements
ok  	github.com/grafana/mimir/pkg/ruler	13.534s	coverage: 35.3% of statements
```

```
ok  	github.com/grafana/mimir/pkg/storegateway/indexheader	10.476s	coverage: 81.7% of statements
ok  	github.com/grafana/mimir/pkg/storegateway/indexheader	9.518s	coverage: 81.9% of statements
```

```
ok  	github.com/grafana/mimir/pkg/util/validation	0.541s	coverage: 58.8% of statements
ok  	github.com/grafana/mimir/pkg/util/validation	0.684s	coverage: 58.0% of statements
```

I don't think any of the above are concerning (and in some cases show an increase). The most notable is the PB which is generated anyway.

**Comment by pstibrany** [comment]
https://github.com/grafana/mimir/commit/21080f83f8116926f52205d2f0d90311bd522762

I would prefer to reduce dependencies on `validation.Overrides`, not introduce new dependencies on it, even when it's just tests. Why wasn't approach with `ruleLimits` good enough?

**Comment by dimitarvdimitrov** [comment]
I left a comment on it because it was code duplication. What is your concern @pstibrany?

**Pull request merged**
