### PR TITLE
Vendor in new grafana/alerting package

### PR DESCRIPTION
**Pull request by fayzal-g**
Vendors in https://github.com/grafana/alerting/commit/611a23ff0f7fb38fe1d1b80fde199e82b20dd8a1

### CODE REVIEW

**Review by ying-jeanne — DISMISSED** [review]
I didn't follow the entire feature, but according to what I see here, we return extra httpCode when error to give more details about failure, and include in response. Changes LGTM

**Comment by ying-jeanne** [comment]
seems integration tests failed, will let you fix them.

**Review by santihernandezc — APPROVED** [review]
LGTM

**Review by santihernandezc — APPROVED** [review]
LGTM

**Review by ying-jeanne — APPROVED** [review]
lgtm

**Pull request merged**
