### PR TITLE
Don't free buffers after reading query stream

### PR DESCRIPTION
**Pull request by colega**
#### What this PR does

While the write path has been carefully crafted to make sure that we don't keep references to the strings backed by arrays with data from grpc stream (because it would cause a memory leak), this doesn't seem to be the case in the query path, where some tests started failing after we started to reuse those backing arrays through the usage of memory buffers implemented in the new gRPC library.

This change reverts the buffer freeing, means that it won't be recycled (and will be garbage collected) to ensure data correctness, while we investigate where the data references are kept.

#### Which issue(s) this PR fixes or relates to

Follow up on https://github.com/grafana/mimir/pull/9401

#### Checklist

- [ ] Tests updated.
- [ ] Documentation added.
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [ ] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

### CODE REVIEW

**Comment by colega** [comment]
There was no changelog entry in https://github.com/grafana/mimir/pull/9401 so nothing to update here.

**Review by bboreham — APPROVED** [review]
Seems legit.  I guess we should take a look at the profiles once it gets into use.

**Review by narqo — APPROVED** [review]
🔥 Works for me

> where some tests started failing after we started to reuse those backing arrays through the usage of memory buffers implemented in the new gRPC library

For the history #9718 shows some details about which tests

**Comment by colega** [comment]
It's also concerning that only those tests failed 😱

**Pull request merged**
