### PR TITLE
Update thanos vendor to latest grafana/thanos@out-of-order commit

### LINKED ISSUE #2229: Azure blob storage client buffers entire file in memory
#### Describe the bug

Compactors download TSDB files to a local disk before working on them. When running in Azure, they use the `azure.Bucket` implementation of the `objstore.Bucket` interface. It turns out that the method being used to download these files [buffers them entirely in memory](https://github.com/grafana/mimir/blob/3fe1f4262cca31c0e7910097d574e643bb3f67c6/vendor/github.com/thanos-io/thanos/pkg/objstore/azure/azure.go#L336). This means that compactors are often OOM killed while trying to run since they need to buffer TSDB files in memory (which can get quite large).

#### To Reproduce

N/A

#### Expected behavior

The Azure blob storage client shouldn't store an entire file in memory. The GCS and S3 clients appear to return an `io.ReaderCloser` implementation that fetches portions of the file as needed, avoiding storing it entirely in memory.

#### Environment

- Infrastructure: Azure managed Kubernetes
- Deployment tool: jsonnet

#### Additional Context

Heap dump attached
[heap.zip](https://github.com/grafana/mimir/files/8976470/heap.zip)

### LINKED ISSUE #2232: Try to avoid the additional GetBlobProperties call in Azure client
#### Is your feature request related to a problem? Please describe.

For each API request to the object storage (counted in `thanos_objstore_bucket_operations_total` metric), the Thanos Azure client makes an additional GetBlobProperties call to retrieve the object size, causing a discrepancy between the number of requests reported by Azure and the previous metric, which is problematic as we bill based on number of requests.

This is also caused by https://github.com/grafana/mimir/issues/2231

#### Describe the solution you'd like

One of:
- Further investigate Azure client implementation to see if there’s any way to avoid the additional GetBlobProperties call there (may be fixed with https://github.com/grafana/mimir/issues/2229 since the object size is retrieved so that Get/GetRange can fetch the whole range/blob into memory)
- Open an issue in the [Azure repo](https://github.com/Azure/azure-storage-blob-go) to suggest changes to optionally pass the object size from outside (when the caller already knows it)

#### Additional context

Azure client makes another call to GetBlobProperties to get the object size:
https://github.com/Azure/azure-storage-blob-go/blob/a95cc9323b2c1273a3e088be4a520d4a95a40dd8/azblob/highlevel.go#L200-L205

### PR DESCRIPTION
**Pull request by 56quarters**
Signed-off-by: Nick Pillitteri <nick.pillitteri@grafana.com>

#### What this PR does

Specifically, we want to pull in thanos-io/thanos#5451 for Azure blob
storage improvements.

#### Which issue(s) this PR fixes or relates to

Fixes #2229
Fixes #2232

#### Checklist

- [ ] Tests updated
- [ ] Documentation added
- [X] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by 56quarters** [comment]
I did aa check of the dependencies that saw major version increases, we don't use any of them directly.

**Comment by pracucci** [comment]
Anything worth to note (or focus on when reviewing) among the Thanos changes? I can see many of them.

**Comment by 56quarters** [comment]
> > Anything worth to note (or focus on when reviewing) among the Thanos changes? I can see many of them.
> 
> The only relevant one to me looks like [thanos-io/thanos@79ab7c6](https://github.com/thanos-io/thanos/commit/79ab7c65cb4b66b9dcc4fa537cb43b00cc65066c), downloading and uploading blocks in parallel.

Seems potentially useful to expose to speed up compactors but I think that can be done in a follow up PR. Created an issue here https://github.com/grafana/mimir/issues/2421

**Review by pracucci — APPROVED** [review]
I checked all Thanos changes, and briefly checked all other changes (except for the MD5 assembler). Nothing particularly stands out to me, so LGTM!

**Pull request merged**
