### PR TITLE
Remove automation to build rpm and deb packages

### PR DESCRIPTION
**Pull request by pracucci**
**What this PR does**:
We agreed on not releasing rpm and deb packages at launch. In this PR I'm removing the old automation we had to build them.

**Which issue(s) this PR fixes**:
N/A

**Checklist**

- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by proffalken** [comment]
FWIW it would be great to see these as returned as a deployment option, especially for those of us who build images for using EC2 or similar as opposed to running on k8's.

There's a good discussion around this on slack at https://grafana.slack.com/archives/C039863E8P7/p1648716762030619

**Comment by wilfriedroset** [comment]
Same here, I'm maintaining my own packaging for debian to run Mimir on baremetal. All of it is based [Cortex](https://github.com/cortexproject/cortex/tree/master/packaging/deb)

**Comment by pracucci** [comment]
@proffalken @wilfriedroset I created an issue about it https://github.com/grafana/mimir/issues/1687. Anyone willing to re-introduce them, starting from the previous code?

**Comment by wilfriedroset** [comment]
I will try to implement something

**Pull request merged**
