### PR TITLE
Use centralized make-docs script from Writers' Toolkit

### PR DESCRIPTION
**Pull request by jdbaldry**
- Adds ability to build multiple projects simultaneously using, for example, `make docs PROJECTS='grafana grafana-cloud'`.
- Adds `make doc-validator` which runs [`doc-validator`](https://github.com/grafana/technical-documentation/tree/main/tools/cmd/doc-validator) on all documentation.

The `make-docs` script used by `make docs` should have feature parity with the existing target.
It logs the browser URL for the served documentation and also inserts a redirect from the `/docs/<PROJECT>/` to `/docs/<PROJECT>/<VERSION>/`.

Using a centralized script will help ensure consistency in workflow across all projects.

Signed-off-by: Jack Baldry <jack.baldry@grafana.com>

### CODE REVIEW

**Comment by lamida** [comment]
The CHANGELOG has just been cut to prepare for the next Mimir release. Please rebase `main` and eventually move the CHANGELOG entry added / updated in this PR to the top of the CHANGELOG document. Thanks!

**Comment by jdbaldry** [comment]
> The CHANGELOG has just been cut to prepare for the next Mimir release. Please rebase `main` and eventually move the CHANGELOG entry added / updated in this PR to the top of the CHANGELOG document. Thanks!

Hi @lamida, there is no CHANGELOG entry associated with this PR.

**Comment by lamida** [comment]
@jdbaldry that comment is automated from [a script](https://github.com/grafana/mimir/blob/main/tools/release/notify-changelog-cut.sh). Unfortunately, the script just sends the comments to all opened PRs. Just ignore it if it is not relevant to this PR. :smiley:

**Review by pracucci — APPROVED** [review]
I took a quick look and LGTM. I also guess this is mostly a copy-paste across all projects you manage.

**Comment by pracucci** [comment]
@jdbaldry However, could look at the failing `make` commands because of `variables.mk` not being loaded apparently?

**Comment by jdbaldry** [comment]
Thanks for taking a look Marco. The top level Make targets should be fixed now.

**Review by krajorama — APPROVED** [review]
LGTM

**Pull request merged**
