### PR TITLE
[WIP] PromQL: Add support for quoted metric and label names

### PR DESCRIPTION
**Pull request by ywwg**
DO NOT REVIEW / MERGE

First draft of adding support for quoted metric names and labels for promql. 

Adds support for 
`{"my.quoted.metric", "my.dotted.label"="whatever"}`

Metric name must be the first item in the bracketed list. 

Adds a single correctness test. All other tests still pass.

### CODE REVIEW

**Comment by lamida** [comment]
The CHANGELOG has just been cut to prepare for the next Mimir release. Please rebase `main` and eventually move the CHANGELOG entry added / updated in this PR to the top of the CHANGELOG document. Thanks!

**Comment by ywwg** [comment]
part of https://github.com/grafana/query-squad/issues/387

**Comment by ywwg** [comment]
This PR will be open when the changes to Prometheus are made

**Comment by ywwg** [comment]
accidentally deleted

**Pull request closed without merging**
