### PR TITLE
Upgrade prometheus/alertmanager to latest

### PR DESCRIPTION
**Pull request by alexweav**
#### What this PR does

This PR upgrades the `prometheus/alertmanager` dependency. This is primarily to support future work to solve https://github.com/grafana/mimir/issues/4200, which relies on recent changes to the AM's `template` package. However, it also incorporates a few fixes and extensions to notifiers.

#### Which issue(s) this PR fixes or relates to

contrib https://github.com/grafana/mimir/issues/4200

#### Checklist

- [x] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by pracucci — COMMENTED** [review]
Thanks for opening this PR. A couple of things:
1. Please rebase `main`: we've merged a Prometheus upgrade few hours ago which also updated some dependencies
2. The updated Alertmanager adds new config options which read content from file. This is forbidden in Mimir (because of security issues) so `WebhookConfig.URLFile` and `TelegramConfig.BotTokenFile` should be forbidden. Please follow the same pattern as in [`validateAlertmanagerConfig`](https://github.com/grafana/mimir/blob/main/pkg/alertmanager/api.go#LL323C1-L323C1) to block these two additional config options.

**Comment by alexweav** [comment]
Thanks for taking a look @pracucci! Feedback is addressed.

**Review by pracucci — APPROVED** [review]
The alertmanager changes LGTM so far!

**Comment by alexweav** [comment]
Upgraded to tip of `prometheus/alertmanager` one more time. The change mentioned above got merged. Plus, a few other dep upgrades :+1:

**Review by stevesg — APPROVED** [review]
Thanks Alex!

**Comment by gotjosh** [comment]
There's two things I was hoping we could do as part of this import:

1. Create a global sums of counters on the silence and nflog operational metrics

I introduced a set of metrics around maintain of these two components to get a better sense on when they fail. I was hoping we could aggregate them to get a better view of when these fail. The metrics are:

```
alertmanager_silences_maintenance_total
alertmanager_silences_maintenance_errors_total
alertmanager_nflog_maintenance_total
alertmanager_nflog_maintenance_errors_total
```

2. Add the reason label to `notifications_failed_total`

We added a new label called `reason` to these metrics to help users of the platform identify what went wrong with their integrations. I think this pretty valuable to expose all the way down to grafana cloud to help our users identify why their integrations are failing.

**Pull request merged**
