### PR TITLE
[release-2.10] Bump github.com/minio/minio-go/v7 from 7.0.62 to 7.0.63

### PR DESCRIPTION
**Pull request by grafanabot**
Backport 98d7c85c493c28a627362cd12ad4a255c4e0918e from #5888

### CODE REVIEW

**Review by 56quarters — APPROVED** [review]

**Comment by pstibrany** [comment]
Can we add changelog to mention this in rc.1? What exactly does it fix?

**Comment by 56quarters** [comment]
> Can we add changelog to mention this in rc.1? What exactly does it fix?

I guess? We didn't add a changelog entry for the initial PR. Does the presence of an issue (#5878) necessitate a changelog entry for routine version bumps?

**Comment by pstibrany** [comment]
> > Can we add changelog to mention this in rc.1? What exactly does it fix?
> 
> I guess? We didn't add a changelog entry for the initial PR. Does the presence of an issue (#5878) necessitate a changelog entry for routine version bumps?

We don't do "routine version bumps" between release candidates, but we did it here. There must be a reason, and it would be good to document it.

**Comment by colega** [comment]
I'll hold publishing rc.1 until Monday to include that changelog :+1:

**Comment by 56quarters** [comment]
Opened https://github.com/grafana/mimir/pull/5905

**Pull request merged**
