### PR TITLE
[Pull Request Template] change file path

### PR DESCRIPTION
**Pull request by ncharaf**
#### What this PR does
Change the `about-versioning.md` path that used in PR template. The previous link was refering to (https://github.com/docs/sources/mimir/configure/about-versioning.md) ,

It's just a cosmetic changes 

#### Which issue(s) this PR fixes or relates to

Fixes #<issue number>

#### Checklist

- [ ] Tests updated.
- [ ] Documentation added.
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [ ] [`about-versioning.md`](/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

### CODE REVIEW

**Comment by ncharaf** [comment]
With the modification:

- [ ] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

**Review by 56quarters — APPROVED** [review]
Thanks!

**Comment by ncharaf** [comment]
@56quarters  Please can relaunch the tests ? (

Thanks !

**Comment by 56quarters** [comment]
CLA check finally passed, I'll rerun the other actions if they fail and get this merged. Thanks again!

**Comment by ncharaf** [comment]
Yes sure . Thanks again !

**Pull request merged**
