### PR TITLE
Report previously failed shipped blocks in shipper

### PR DESCRIPTION
**Pull request by dimitarvdimitrov**
Signed-off-by: Dimitar Dimitrov <dimitar.dimitrov@grafana.com>

#### What this PR does

When a block upload appears to have failed, but later the shipper
discovers that the upload actually succeeded, the shipper does not
upload it again. But the ingester still reports the block as unhsipped.
This lead to a false positive alert (`MimirIngesterHasUnshippedBlocks`)
and stale value for `cortex_ingester_oldest_unshipped_block_timestamp_seconds`.

This PR changes the shipper to report an upload when it discovers
such a block. This helps with invalidating the cached shipper meta file
and reporting correct metrics.

#### Which issue(s) this PR fixes or relates to

Fixes https://github.com/grafana/mimir/issues/1997

#### Checklist

- [ ] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by dimitarvdimitrov** [comment]
there are other alternatives I considered before making this change:
* return another value from the `Sync` method of the shipper - `confirmedUploads`/`discoveredUploads`; the reason I didn't go with this is that it is difficult to explain the purpose of the return parameter
* return a boolean from `Sync` based on whether the meta file changed; chose not to because it leaks the meta file abstraction

**Review by pstibrany — APPROVED** [review]
I think this fix is good enough. We should add a test. Thank you!

**Review by pracucci — APPROVED** [review]
Good job! I would ❤️ test too.

**Comment by dimitarvdimitrov** [comment]
Added tests in 008655011fb764c499bd1677a8a34fbd1c5229ee, I had to add a bucket which pretends to fail on meta.json uploads. The name I chose for that is `deceivingUploadBucket`, open to suggestions for the name.

**Comment by pstibrany** [comment]
Thank you. `deceivingUploadBucket` is funny, but why not :)

**Pull request merged**
