### PR TITLE
Helm : add hpa resource for the querier

### PR DESCRIPTION
**Pull request by QuantumEnigmaa**
#### What this PR does

This PR adds a hpa object for the `querier` component in the `mimir-distributed` helm chart. Since Keda might not be used by several users, having a default hpa would enable to have horizontal autoscaling for the `querier` without needing additional apps installed.

Similar PR for the distributor : https://github.com/grafana/mimir/pull/7839

#### Checklist

- [ ] Tests updated.
- [ ] Documentation added.
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [ ] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

### CODE REVIEW

**Comment by QuantumEnigmaa** [comment]
@dimitarvdimitrov Sorry to ping you again :pray:

**Comment by dimitarvdimitrov** [comment]
i'm not super sure about adding multiple ways for autoscaling. Wouldn't that make the chart less easy to work with because now you have to also understand and choose which autoscaling you need?

would like to hear from @krajorama as well.

**Comment by QuantumEnigmaa** [comment]
> Wouldn't that make the chart less easy to work with because now you have to also understand and choose which autoscaling you need?

I think it's quite the opposite because with this proposed change users would find themselves in 2 different situation when it comes to autoscaling : 

* Either they already have Keda installed on their cluster and will be happy to find the current existing field in the values which gives them the possibility to add a ScaledObject resource directly from the values 
* Or they either don't have Keda installed and don't plan on using it in a near future but still want a quick and easy autoscaling solution such as the one present for the gateway component. I think they'll like to have this possibility embedded in the values instead of having to add the resource as an extra-object.

> What's the difference between just the operator creating an HPA yaml and installing that along with mimir? There is the extraObjects key in the values you can use for that.

I'm not sure which operator you're referring to but as I mentioned above, in my opinion being able to create an hpa resource from the values is a time saver (it avoids the user to have to go through the extra-objects).

**Comment by dimitarvdimitrov** [comment]
I don't think installing Keda is an unreasonable requirement. The setup cost is low and iot has low overhead to maintain.

Adding more ways to the same thing looks like a maintenance burden on the helm chart. We're understaffed on helm maintainers and I'd like to concentrate efforts on the existing keda support instead of adding more features.

**Pull request closed without merging**
