### PR TITLE
Release mimir-distributed Helm chart 5.2.0-weekly.262

### PR DESCRIPTION
**Pull request by grafanabot**
Automated PR created by [helm-weekly-release-pr.yaml](https://github.com/grafana/mimir/blob/main/.github/workflows/helm-weekly-release-pr.yaml)

### CODE REVIEW

**Comment by dimitarvdimitrov** [comment]
why is this in draft @krajorama ?

**Comment by krajorama** [comment]
> why is this in draft @krajorama ?

@dimitarvdimitrov I have to rebase it, plus now it should have https://github.com/prometheus/prometheus/pull/13062 as well

**Comment by dimitarvdimitrov** [comment]
the bot should be rebasing it every day at around 10 UTC

the PR you linked to isn't merged. Do you mean it or the ring buffer fix?

**Review by dimitarvdimitrov — APPROVED** [review]
agreed with @krajorama privately to merge this; it is unlikely that the linked PR is on Prometheus main today

**Pull request merged**
