### PR TITLE
Dependency: Update go version in Mimir to 1.21.0

### PR DESCRIPTION
**Pull request by ying-jeanne**
#### Which issue(s) this PR fixes or relates to

Fixes #<issue number>

#### Checklist

- [x] Tests updated
- [x] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by pstibrany** [comment]
Testing new workflow 👍 🤞

**Review by aknuds1 — COMMENTED** [review]
The changelog should also have an entry.

**Comment by ying-jeanne** [comment]
I saw that github action is appending another commit with my identifier, it works fine. But I noticed the dependabot is not updating the dockerfile automatically, the reason is https://github.com/grafana/mimir/network/updates/708883608, dependabot.yml is expecting the path exact for docker file in the repo. We can't activate the docker update for the entire repo apparently, just file by file.

**Review by aknuds1 — APPROVED** [review]

**Comment by pstibrany** [comment]
> **Not building new version of **. This PR modifies , but the image already exists.

This comment seems broken.

**Pull request merged**
