### PR TITLE
Run conftest policies against Jsonnet-generated manifests

### PR DESCRIPTION
**Pull request by charleskorn**
#### What this PR does

This PR adds running the existing conftest policies used for the Helm chart against our test suite of Jsonnet-generated manifests.

The policies related to pod security standards introduced in #3007 are disabled for Jsonnet as our Jsonnet-generated manifests are currently not compliant with these standards.

This PR also improves how conftest policy failures are shown: rather than including a JSON representation of the entire object in the error, the kind and name of the object (eg. `Deployment/distributor`) is included instead.

#### Which issue(s) this PR fixes or relates to

Split from #5098

#### Checklist

- [n/a] Tests updated
- [n/a] Documentation added
- [n/a] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by krajorama — APPROVED** [review]
One thing to note is that for helm we can take into account the user input, that is make some tests depend on how the helm chart is used. See https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/templates/values-for-rego-tests.yaml extra pseudo manifest. Not sure how this will apply to jsonnet - how you'd be able to get to the input side? Anyway, good job.

**Comment by charleskorn** [comment]
> Nice work! Do you think we should be running the jsonnet assertions in CI? I think that will make it easier to adhere to them, plus they currently all pass (with your change for `disable_restricted_security_context_checks`).

Yep, they'll run in CI as part of the [`Check Jsonnet Tests` step](https://github.com/grafana/mimir/blob/bd2e5d17e2d510e29b67879f458c4e4cbe2cafdc/.github/workflows/test-build-deploy.yml#L89), which calls `make check-jsonnet-tests`, which runs the conftest checks. (This follows the same pattern as the Helm-related Make targets.)

**Comment by charleskorn** [comment]
> One thing to note is that for helm we can take into account the user input, that is make some tests depend on how the helm chart is used. See https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/templates/values-for-rego-tests.yaml extra pseudo manifest. Not sure how this will apply to jsonnet - how you'd be able to get to the input side?

Looks like this is only used to see if the target environment is OpenShift at the moment. Do we support running the Jsonnet-generated manifests on OpenShift?

**Comment by charleskorn** [comment]
Given the approvals, I'm going to merge this, but still open to any follow-up feedback or suggestions in response to your comments @dimitarvdimitrov @krajorama.

**Pull request merged**
