### PR TITLE
Fix segmentation fault in Ingester.LabelValues response marshaling

### LINKED ISSUE #7897: Ingester segfault marshaling a LabelValuesResponse
#### Describe the bug

We have several instances of this happening where ingesters segfault while attempting to marshal a `LabelValuesResponse`. It will often take out several ingesters. Sometimes these ingesters are in different zones of the same cluster, sometimes they're in the same zone.

#### To Reproduce
I don't have a reproduction at this time.

#### Environment

- Infrastructure: Kube

#### Additional Context

```
2024-04-09 06:51:51.771	unexpected fault address 0x7976968b824e
2024-04-09 06:51:51.771	fatal error: fault
2024-04-09 06:51:51.773	[signal SIGSEGV: segmentation violation code=0x1 addr=0x7976968b824e pc=0x472ea1]
2024-04-09 06:51:51.773	
2024-04-09 06:51:51.773	goroutine 3390042 [running]:
2024-04-09 06:51:51.773	runtime.throw({0x32cb84f?, 0xc083471538?})
2024-04-09 06:51:51.773		$GOROOT/src/runtime/panic.go:1077 +0x5c fp=0xc0834714c8 sp=0xc083471498 pc=0x43ba1c
2024-04-09 06:51:51.773	runtime.sigpanic()
2024-04-09 06:51:51.773		$GOROOT/src/runtime/signal_unix.go:875 +0x285 fp=0xc083471528 sp=0xc0834714c8 pc=0x452a25
2024-04-09 06:51:51.773	runtime.memmove()
2024-04-09 06:51:51.773		$GOROOT/src/runtime/memmove_amd64.s:184 +0x141 fp=0xc083471530 sp=0xc083471528 pc=0x472ea1
2024-04-09 06:51:51.773	github.com/grafana/mimir/pkg/ingester/client.(*LabelValuesResponse).MarshalToSizedBuffer(0xc0eb628078, {0xc137890000, 0x2d6a64, 0x2d6a64})
2024-04-09 06:51:51.773		/drone/src/vendor/github.com/grafana/mimir/pkg/ingester/client/ingester.pb.go:5540 +0xdc fp=0xc083471570 sp=0xc083471530 pc=0x1cda43c
2024-04-09 06:51:51.773	github.com/grafana/mimir/pkg/ingester/client.(*LabelValuesResponse).Marshal(0xc0eb628078)
2024-04-09 06:51:51.773		/drone/src/vendor/github.com/grafana/mimir/pkg/ingester/client/ingester.pb.go:5520 +0x65 fp=0xc0834715b0 sp=0xc083471570 pc=0x1cda1c5
2024-04-09 06:51:51.773	google.golang.org/protobuf/internal/impl.legacyMarshal({{}, {0x3a9f3c8, 0xc0eab27590}, {0x0, 0x0, 0x0}, 0x0})
2024-04-09 06:51:51.773		/drone/src/vendor/google.golang.org/protobuf/internal/impl/legacy_message.go:407 +0x9e fp=0xc083471630 sp=0xc0834715b0 pc=0x651ffe
2024-04-09 06:51:51.773	google.golang.org/protobuf/proto.MarshalOptions.marshal({{}, 0x8?, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0x3a9f3c8, 0xc0eab27590})
2024-04-09 06:51:51.773		/drone/src/vendor/google.golang.org/protobuf/proto/encode.go:166 +0x25d fp=0xc0834716d0 sp=0xc083471630 pc=0x5e43dd
2024-04-09 06:51:51.773	google.golang.org/protobuf/proto.MarshalOptions.MarshalAppend({{}, 0x40?, 0x25?, 0x19?}, {0x0, 0x0, 0x0}, {0x3a4d480?, 0xc0eab27590?})
2024-04-09 06:51:51.773		/drone/src/vendor/google.golang.org/protobuf/proto/encode.go:125 +0x73 fp=0xc083471718 sp=0xc0834716d0 pc=0x5e4033
2024-04-09 06:51:51.773	github.com/golang/protobuf/proto.marshalAppend({0x0, 0x0, 0x0}, {0x79759e28b350?, 0xc0eb628078?}, 0x40?)
2024-04-09 06:51:51.773		/drone/src/vendor/github.com/golang/protobuf/proto/wire.go:40 +0x9e fp=0xc083471798 sp=0xc083471718 pc=0x9a38be
2024-04-09 06:51:51.773	github.com/golang/protobuf/proto.Marshal(...)
2024-04-09 06:51:51.773		/drone/src/vendor/github.com/golang/protobuf/proto/wire.go:23
2024-04-09 06:51:51.773	google.golang.org/grpc/encoding/proto.codec.Marshal({}, {0x3192540?, 0xc0eb628078})
2024-04-09 06:51:51.773		/drone/src/vendor/google.golang.org/grpc/encoding/proto/proto.go:45 +0x4d fp=0xc0834717f0 sp=0xc083471798 pc=0xa4292d
2024-04-09 06:51:51.773	google.golang.org/grpc/encoding/proto.(*codec).Marshal(0x32cbcd7?, {0x3192540?, 0xc0eb628078?})
2024-04-09 06:51:51.773		<autogenerated>:1 +0x31 fp=0xc083471810 sp=0xc0834717f0 pc=0xa42b11
2024-04-09 06:51:51.773	google.golang.org/grpc.encode({0x7975a8355e90?, 0x540c3e0?}, {0x3192540?, 0xc0eb628078?})
2024-04-09 06:51:51.773		/drone/src/vendor/google.golang.org/grpc/rpc_util.go:633 +0x3e fp=0xc083471860 sp=0xc083471810 pc=0xaa2d9e
2024-04-09 06:51:51.773	google.golang.org/grpc.(*Server).sendResponse(0xc000ff9a00, {0x3a6c760, 0xc04bf1ced0}, {0x3a8f780, 0xc0c3caa9c0}, 0xc0671f50e0, {0x3192540?, 0xc0eb628078}, {0x0, 0x0}, ...)
2024-04-09 06:51:51.773		/drone/src/vendor/google.golang.org/grpc/server.go:1149 +0x9b fp=0xc083471970 sp=0xc083471860 pc=0xaa8a5b
2024-04-09 06:51:51.773	google.golang.org/grpc.(*Server).processUnaryRPC(0xc000ff9a00, {0x3a6c760, 0xc04bf1ccf0}, {0x3a8f780, 0xc0c3caa9c0}, 0xc0671f50e0, 0xc000d513e0, 0x53a7cb0, 0x0)
2024-04-09 06:51:51.773		/drone/src/vendor/google.golang.org/grpc/server.go:1432 +0xf4a fp=0xc083471d58 sp=0xc083471970 pc=0xaaa0ea
2024-04-09 06:51:51.773	google.golang.org/grpc.(*Server).handleStream(0xc000ff9a00, {0x3a8f780, 0xc0c3caa9c0}, 0xc0671f50e0)
2024-04-09 06:51:51.773		/drone/src/vendor/google.golang.org/grpc/server.go:1796 +0xfec fp=0xc083471f30 sp=0xc083471d58 pc=0xaaf0ac
2024-04-09 06:51:51.773	google.golang.org/grpc.(*Server).serveStreams.func2.1()
2024-04-09 06:51:51.773		/drone/src/vendor/google.golang.org/grpc/server.go:1029 +0x8b fp=0xc083471f98 sp=0xc083471f30 pc=0xaa7eab
2024-04-09 06:51:51.773	google.golang.org/grpc.(*Server).serverWorker(0xc000ff9a00)
2024-04-09 06:51:51.773		/drone/src/vendor/google.golang.org/grpc/server.go:632 +0x25 fp=0xc083471fc8 sp=0xc083471f98 pc=0xaa49a5
2024-04-09 06:51:51.773	google.golang.org/grpc.(*Server).serverWorker.func1()
2024-04-09 06:51:51.773		/drone/src/vendor/google.golang.org/grpc/server.go:634 +0x25 fp=0xc083471fe0 sp=0xc083471fc8 pc=0xaa4a85
2024-04-09 06:51:51.773	runtime.goexit()
2024-04-09 06:51:51.773		$GOROOT/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc083471fe8 sp=0xc083471fe0 pc=0x471f61
2024-04-09 06:51:51.773	created by google.golang.org/grpc.(*Server).serverWorker in goroutine 2967518
2024-04-09 06:51:51.773		/drone/src/vendor/google.golang.org/grpc/server.go:634 +0xa6
```

### PR DESCRIPTION
**Pull request by seizethedave**
#### What this PR does

This PR fixes a segmentation fault (see #7897) that happens when ongoing compaction in the ingester unmaps an index file that an in-flight `Ingester.LabelValues` response hasn't yet marshaled.

I am doing the simplest thing here which is to make a copy of all of the label value strings.

I did some analysis on the `Ingester.LabelValues` usage we see. Some ingester pods do see ~200 RPS of LabelValues invocations. The vast majority of calls are in the smaller response sizes. But, we do some some regular periodic LabelValues calls where the response is >25mb. (And sometimes >250mb.) These larger ones are just a few times per minute when they do happen, so I suspect it won't be problematic. But I welcome additional points of view.

#### Which issue(s) this PR fixes or relates to

Fixes #7897

#### Checklist

- [ ] Tests updated.
- [ ] Documentation added.
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [ ] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

### CODE REVIEW

**Comment by aknuds1** [comment]
Did you conclude against a custom gRPC codec, then?

**Comment by seizethedave** [comment]
Yeah, if it is unlikely to degrade things, then the decreased fiddly-ness and complexity of this fix seems preferable to me.

**Review by pstibrany — APPROVED** [review]

**Review by aknuds1 — CHANGES_REQUESTED** [review]
Looks good, except the changelog entry needs to point to the PR.

**Review by aknuds1 — APPROVED** [review]
LGTM!

**Pull request merged**
