### PR TITLE
Allow using Thanos AWS SDK auth mode

### PR DESCRIPTION
**Pull request by sylr**
#### What this PR does

Allow using Thanos AWS SDK auth mode.

#### Which issue(s) this PR fixes or relates to

Fixes #<issue number>

#### Checklist

- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by sylr** [comment]
It allows to use the AWS STS assume role capabilities implemented in the AWS SDK which allows access to buckets in other accounts without the use of access and secret keys.

**Comment by pdf** [comment]
This would allow us to use IAM Roles via Service Accounts in EKS, which is strongly preferable over access keys, and the change looks very clean.

**Comment by pracucci** [comment]
I'm going to close this stale PR. Over the past few months, we've seen several people from the community running Mimir in EKS using IAM, so before proceeding with this PR I would like to learn more what doesn't work with the current state of the code.

**Comment by sylr** [comment]
You have seen people running mimir in EKS either using insecure access keys or using S3 buckets in the **same** AWS account as the target S3.

**Pull request closed without merging**
