### PR TITLE
Docs: Helm: prepare update doc links for 2.7.x

### PR DESCRIPTION
**Pull request by krajorama**
- [x] Fix configuration parameter reference link. Ref: #4276 Update link to HA dedup setup with Consul to be a relref, since it was moved into the Helm docs. Ref: #4338

Used:
```
find . -name "*.md" -a -not -path "./release-notes/*" | xargs sed -i -- 's%/v2.6.x/%/v2.7.x/%g'
```
and my eyes.

### CODE REVIEW

**Comment by krajorama** [comment]
wait for #4481

**Comment by osg-grafana** [comment]
We need to fix the path names too, after #4481 merges into `main`.

**Comment by krajorama** [comment]
Do this on the Helm release branch as main has deviated

**Comment by osg-grafana** [comment]
> Do this on the Helm release branch as main has deviated

Why not on `main` and cherry pick into release branch?

**Review by osg-grafana — APPROVED** [review]

**Pull request merged**
