### PR TITLE
Migrate fpm to nfpm

### LINKED ISSUE #2986: Move rpm/deb Mimir package builds from fpm to nfpm
#### Is your feature request related to a problem? Please describe.

Other Grafana projects, Loki, Tempo, and synthetic monitoring, have moved to using [nfpm](https://github.com/goreleaser/nfpm) for packaging the project as rpm and deb files while we are still using fpm.

#### Describe the solution you'd like
migrate the package builds to use nfpm/gorelaser similar to Tempo or Loki or Synthetic Monitoring

#### Describe alternatives you've considered

Keep using fpm which is lacking Grafana internal support and it's based on ruby rather than Go

#### Additional context
[Synthetic Monitoring Packaging](https://github.com/grafana/synthetic-monitoring-agent/blob/main/.goreleaser.yaml)
[Tempo Packaging](https://github.com/grafana/tempo/blob/main/.goreleaser.yml)
[Loki Packaging](https://github.com/grafana/loki/blob/main/tools/packaging/nfpm.jsonnet)

### PR DESCRIPTION
**Pull request by bubu11e**
#### What this PR does

This PR migrate Grafana Mimir packaging solution from FPM to NFPM in three steps:
- Migrating the tooling to NFPM with as less as possible of changes to the builded packages
- Rationalize packages dependencies using NFPM capabilities and a bit of templating to avoid divergences between deb and rpm packaging.
- Create packages for other mimir binaries like mimirtool or mimir-continous-test

Other Grafana projects already uses NFPM like Loki.

#### Which issue(s) this PR fixes or relates to

Fixes #2986 

#### More details

You will find a packages attached to this PR to test yourself.
[deb_packages.tar.gz](https://github.com/grafana/mimir/files/10381778/deb_packages.tar.gz)
[rpm_packages.tar.gz](https://github.com/grafana/mimir/files/10381779/rpm_packages.tar.gz)

### CODE REVIEW

**Comment by 56quarters** [comment]
The CHANGELOG has just been cut to prepare for the next Mimir release. Please rebase `main` and eventually move the CHANGELOG entry added / updated in this PR to the top of the CHANGELOG document. Thanks!

**Comment by bubu11e** [comment]
> The CHANGELOG has just been cut to prepare for the next Mimir release. Please rebase `main` and eventually move the CHANGELOG entry added / updated in this PR to the top of the CHANGELOG document. Thanks!

Hi, its done. Thanks

**Comment by pracucci** [comment]
Hi @bubu11e! Thanks for working on this and sorry for the late reply. The main struggle we (maintainers) have reviewing this PR is that we don't use these packages at Grafana Labs and we have no hands-on experience with them.

So my question is: which manual testing did you do on the new packages? Have you installed them and can you confirm Mimir gets successfully installed?

Thanks!

**Comment by bubu11e** [comment]
> Hi @bubu11e! Thanks for working on this and sorry for the late reply. The main struggle we (maintainers) have reviewing this PR is that we don't use these packages at Grafana Labs and we have no hands-on experience with them.
> 
> So my question is: which manual testing did you do on the new packages? Have you installed them and can you confirm Mimir gets successfully installed?
> 
> Thanks!

Hi,

I did install both packages (debian and rpm) on architecture x86_64 and checked that Mimir was installed and started. I do not have hardware to test other architecture but i assume it would work as the package is built the same way.

Regards,

**Comment by pracucci** [comment]
That's enough for me, thanks! Going to merge it and thanks 🤗

**Review by pracucci — APPROVED** [review]

**Pull request merged**
