### PR TITLE
Helm: fix namespace issues

### LINKED ISSUE #2045: helm: Not all resources respect the release namespace
#### Describe the bug

Not all resources declare their namespaces. Because of this running `helm template --namespace foo .. | kubectl apply -f -` creates the resources in the current namespace, not in `foo`

#### To Reproduce

1. Checkout any version of the chart. `cd operations/helm/charts/mimir-distributed`
2. Have a kubernetes cluster where the `foo` namespace doesn't exist.
3. `helm template . --values values.yaml --namespace foo | kubectl apply -f -`
4. Some resources get created in the current namespace, some go to the `foo` namespace.
   <details>

   <summary>Running the command above</summary>

    ```
    podsecuritypolicy.policy/release-name-mimir created
    poddisruptionbudget.policy/release-name-mimir-ingester created
    poddisruptionbudget.policy/release-name-mimir-store-gateway created
    serviceaccount/release-name-grafana-agent-operator created
    serviceaccount/release-name-minio-update-prometheus-secret created
    serviceaccount/release-name-mimir created
    secret/release-name-minio created
    secret/release-name-mimir-metrics-instance-usernames created
    secret/release-name-mimir-config created
    configmap/release-name-minio created
    configmap/release-name-mimir-nginx created
    configmap/release-name-mimir-runtime created
    persistentvolumeclaim/release-name-minio created
    clusterrole.rbac.authorization.k8s.io/release-name-grafana-agent-operator created
    clusterrole.rbac.authorization.k8s.io/release-name-mimir-grafana-agent created
    clusterrolebinding.rbac.authorization.k8s.io/release-name-grafana-agent-operator created
    clusterrolebinding.rbac.authorization.k8s.io/release-name-mimir-grafana-agent created
    role.rbac.authorization.k8s.io/release-name-minio-update-prometheus-secret created
    role.rbac.authorization.k8s.io/release-name-mimir created
    rolebinding.rbac.authorization.k8s.io/release-name-minio-update-prometheus-secret created
    rolebinding.rbac.authorization.k8s.io/release-name-mimir created
    service/release-name-minio created
    service/release-name-mimir-alertmanager-headless created
    service/release-name-mimir-alertmanager created
    service/release-name-mimir-compactor created
    service/release-name-mimir-distributor-headless created
    service/release-name-mimir-distributor created
    service/release-name-mimir-gossip-ring created
    service/release-name-mimir-ingester-headless created
    service/release-name-mimir-ingester created
    service/release-name-mimir-nginx created
    service/release-name-mimir-overrides-exporter created
    service/release-name-mimir-querier created
    service/release-name-mimir-query-frontend-headless created
    service/release-name-mimir-query-frontend created
    service/release-name-mimir-ruler created
    service/release-name-mimir-store-gateway-headless created
    service/release-name-mimir-store-gateway created
    deployment.apps/release-name-grafana-agent-operator created
    deployment.apps/release-name-minio created
    deployment.apps/release-name-mimir-distributor created
    deployment.apps/release-name-mimir-nginx created
    deployment.apps/release-name-mimir-overrides-exporter created
    deployment.apps/release-name-mimir-querier created
    deployment.apps/release-name-mimir-query-frontend created
    deployment.apps/release-name-mimir-ruler created
    statefulset.apps/release-name-mimir-alertmanager created
    statefulset.apps/release-name-mimir-compactor created
    statefulset.apps/release-name-mimir-ingester created
    statefulset.apps/release-name-mimir-store-gateway created
    serviceaccount/grafana-agent-test-sa created
    clusterrole.rbac.authorization.k8s.io/grafana-agent-test-cr created
    clusterrolebinding.rbac.authorization.k8s.io/grafana-agent-test-crb created
    pod/grafana-agent-test-probe created
    job.batch/release-name-minio-make-bucket-job created
    [unable to recognize "STDIN": no matches for kind "GrafanaAgent" in version "monitoring.grafana.com/v1alpha1", unable to recognize "STDIN": no matches for kind "MetricsInstance" in version "monitoring.grafana.com/v1alpha1", unable to recognize "STDIN": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"]
    Error from server (NotFound): error when creating "STDIN": namespaces "foo" not found
    Error from server (NotFound): error when creating "STDIN": namespaces "foo" not found
    Error from server (NotFound): error when creating "STDIN": namespaces "foo" not found
    ```

   </details>

   <details> <summary>Running `kubectl get all --all-namespaces`</summary>

   ```
    NAMESPACE     NAME                                                         READY   STATUS      RESTARTS   AGE
    kube-system   pod/local-path-provisioner-5ff76fc89d-rqbln                  1/1     Running     0          2m59s
    kube-system   pod/coredns-7448499f4d-6ftq4                                 1/1     Running     0          2m59s
    kube-system   pod/metrics-server-86cbb8457f-n8j88                          1/1     Running     0          2m59s
    kube-system   pod/helm-install-traefik-crd-6m7g9                           0/1     Completed   0          2m59s
    kube-system   pod/helm-install-traefik-vmb5r                               0/1     Completed   0          2m59s
    default       pod/release-name-mimir-query-frontend-66945c574b-2qhc4       0/1     Running     0          2m40s
    kube-system   pod/svclb-traefik-7c42v                                      2/2     Running     0          2m14s
    kube-system   pod/traefik-97b44b794-64rdz                                  1/1     Running     0          2m14s
    default       pod/release-name-mimir-nginx-d4fb8c6ff-9msnn                 1/1     Running     0          2m40s
    default       pod/release-name-mimir-distributor-6c779c6d9d-b85ps          1/1     Running     0          2m40s
    default       pod/release-name-mimir-overrides-exporter-6cf8c459b8-pjfz4   1/1     Running     0          2m40s
    default       pod/grafana-agent-test-probe                                 0/1     Error       0          2m40s
    default       pod/release-name-mimir-compactor-0                           1/1     Running     0          2m40s
    default       pod/release-name-mimir-querier-6fb4f668b9-z928t              0/1     Running     1          2m40s
    default       pod/release-name-mimir-ruler-55f457c7f9-nl6hq                0/1     Running     1          2m40s
    default       pod/release-name-mimir-querier-6fb4f668b9-mgb5n              0/1     Running     1          2m40s
    default       pod/release-name-mimir-alertmanager-0                        0/1     Running     1          2m40s
    default       pod/release-name-mimir-store-gateway-0                       0/1     Running     1          2m40s
    default       pod/release-name-mimir-ingester-2                            0/1     Running     1          2m40s
    default       pod/release-name-mimir-ingester-0                            0/1     Running     1          2m40s
    default       pod/release-name-mimir-ingester-1                            0/1     Running     1          2m40s
    default       pod/release-name-grafana-agent-operator-6d57688796-s7zhb     1/1     Running     1          2m40s
    
    NAMESPACE     NAME                                                 TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
    default       service/kubernetes                                   ClusterIP      10.43.0.1       <none>        443/TCP                      3m14s
    kube-system   service/kube-dns                                     ClusterIP      10.43.0.10      <none>        53/UDP,53/TCP,9153/TCP       3m10s
    kube-system   service/metrics-server                               ClusterIP      10.43.230.150   <none>        443/TCP                      3m9s
    default       service/release-name-minio                           ClusterIP      10.43.226.230   <none>        9000/TCP                     2m41s
    default       service/release-name-mimir-alertmanager-headless     ClusterIP      None            <none>        8080/TCP,9095/TCP,9094/TCP   2m41s
    default       service/release-name-mimir-alertmanager              ClusterIP      10.43.224.166   <none>        8080/TCP,9095/TCP            2m40s
    default       service/release-name-mimir-compactor                 ClusterIP      10.43.4.134     <none>        8080/TCP,9095/TCP            2m40s
    default       service/release-name-mimir-distributor-headless      ClusterIP      None            <none>        9095/TCP                     2m40s
    default       service/release-name-mimir-distributor               ClusterIP      10.43.87.240    <none>        8080/TCP,9095/TCP            2m40s
    default       service/release-name-mimir-gossip-ring               ClusterIP      None            <none>        7946/TCP                     2m40s
    default       service/release-name-mimir-ingester-headless         ClusterIP      None            <none>        9095/TCP                     2m40s
    default       service/release-name-mimir-ingester                  ClusterIP      10.43.23.119    <none>        8080/TCP,9095/TCP            2m40s
    default       service/release-name-mimir-nginx                     ClusterIP      10.43.217.205   <none>        80/TCP                       2m40s
    default       service/release-name-mimir-overrides-exporter        ClusterIP      10.43.168.156   <none>        8080/TCP,9095/TCP            2m40s
    default       service/release-name-mimir-querier                   ClusterIP      10.43.26.74     <none>        8080/TCP,9095/TCP            2m40s
    default       service/release-name-mimir-query-frontend-headless   ClusterIP      None            <none>        8080/TCP,9095/TCP            2m40s
    default       service/release-name-mimir-query-frontend            ClusterIP      10.43.250.71    <none>        8080/TCP,9095/TCP            2m40s
    default       service/release-name-mimir-ruler                     ClusterIP      10.43.52.90     <none>        8080/TCP                     2m40s
    default       service/release-name-mimir-store-gateway-headless    ClusterIP      None            <none>        9095/TCP                     2m40s
    default       service/release-name-mimir-store-gateway             ClusterIP      10.43.240.192   <none>        8080/TCP,9095/TCP            2m40s
    kube-system   service/traefik                                      LoadBalancer   10.43.11.161    172.23.0.2    80:32024/TCP,443:30306/TCP   2m14s
    
    NAMESPACE     NAME                           DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
    kube-system   daemonset.apps/svclb-traefik   1         1         1       1            1           <none>          2m14s
    
    NAMESPACE     NAME                                                    READY   UP-TO-DATE   AVAILABLE   AGE
    default       deployment.apps/release-name-minio                      0/1     0            0           2m40s
    default       deployment.apps/release-name-mimir-querier              0/2     2            0           2m40s
    default       deployment.apps/release-name-mimir-query-frontend       0/1     1            0           2m40s
    default       deployment.apps/release-name-mimir-ruler                0/1     1            0           2m40s
    kube-system   deployment.apps/local-path-provisioner                  1/1     1            1           3m10s
    kube-system   deployment.apps/coredns                                 1/1     1            1           3m10s
    kube-system   deployment.apps/metrics-server                          1/1     1            1           3m9s
    kube-system   deployment.apps/traefik                                 1/1     1            1           2m14s
    default       deployment.apps/release-name-mimir-nginx                1/1     1            1           2m40s
    default       deployment.apps/release-name-mimir-distributor          1/1     1            1           2m40s
    default       deployment.apps/release-name-mimir-overrides-exporter   1/1     1            1           2m40s
    default       deployment.apps/release-name-grafana-agent-operator     1/1     1            1           2m40s
    
    NAMESPACE     NAME                                                               DESIRED   CURRENT   READY   AGE
    default       replicaset.apps/release-name-minio-74fb5c5d77                      1         0         0       2m40s
    default       replicaset.apps/release-name-mimir-querier-6fb4f668b9              2         2         0       2m40s
    default       replicaset.apps/release-name-mimir-query-frontend-66945c574b       1         1         0       2m40s
    default       replicaset.apps/release-name-mimir-ruler-55f457c7f9                1         1         0       2m40s
    kube-system   replicaset.apps/local-path-provisioner-5ff76fc89d                  1         1         1       2m59s
    kube-system   replicaset.apps/coredns-7448499f4d                                 1         1         1       2m59s
    kube-system   replicaset.apps/metrics-server-86cbb8457f                          1         1         1       2m59s
    kube-system   replicaset.apps/traefik-97b44b794                                  1         1         1       2m14s
    default       replicaset.apps/release-name-mimir-nginx-d4fb8c6ff                 1         1         1       2m40s
    default       replicaset.apps/release-name-mimir-distributor-6c779c6d9d          1         1         1       2m40s
    default       replicaset.apps/release-name-mimir-overrides-exporter-6cf8c459b8   1         1         1       2m40s
    default       replicaset.apps/release-name-grafana-agent-operator-6d57688796     1         1         1       2m40s
    
    NAMESPACE   NAME                                                READY   AGE
    default     statefulset.apps/release-name-mimir-alertmanager    0/1     2m40s
    default     statefulset.apps/release-name-mimir-ingester        0/3     2m40s
    default     statefulset.apps/release-name-mimir-store-gateway   0/1     2m40s
    default     statefulset.apps/release-name-mimir-compactor       1/1     2m40s
    
    NAMESPACE     NAME                                           COMPLETIONS   DURATION   AGE
    default       job.batch/release-name-minio-make-bucket-job   0/1                      2m40s
    kube-system   job.batch/helm-install-traefik-crd             1/1           44s        3m7s
    kube-system   job.batch/helm-install-traefik                 1/1           48s        3m7s
    ```

   </details>

#### Expected behavior

The whole installations fails because `foo` namespace doesn't exist. Alternatively, if `foo` exists, resources are created in that namespace.

For example the create-bucket-job correctly sets the namespace: https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/templates/minio/create-bucket-job.yaml#L7

Whereas the querier deployment and most other resources dont https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/templates/querier/querier-dep.yaml#L3-L8

#### Environment

- Infrastructure: Kubernetes with k3d
- helm `version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.18.1"}`, 
- kubectl `Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:41:58Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"darwin/arm64"}`
- kubernetes `Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s2", GitCommit:"724ef700bab896ff252a75e2be996d5f4ff1b842", GitTreeState:"clean", BuildDate:"2021-10-05T19:59:29Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/arm64"}`

#### Additional Context

Discussion for including namespace explicitly in resources: https://github.com/helm/helm/issues/5465. The community seems to be in favour of it.

### PR DESCRIPTION
**Pull request by krajorama**
#### What this PR does

Add namespace definitions to kubernetes objects so that helm install works correctly even if the namespace does not exist yet.
Add default namespace definition and default namespace selector for ServiceMonitor objects.

#### Which issue(s) this PR fixes or relates to

Fixes #2045
Based on: #2040

#### Checklist

- [x] Tests updated
- [N/A] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by krajorama** [comment]
Should update minio to a newer version as well to get the namespace definitions in minio subchart templates.

**Review by dimitarvdimitrov — APPROVED** [review]
LGTM, two small nits

**Review by dimitarvdimitrov — APPROVED** [review]
tried to look at changes since last time I reviewed. couldn't find any. lgtm

**Comment by dimitarvdimitrov** [comment]
I testing installing this via helm template and only got the minio resources in the current namespace as opposed to the namespace from the `--namespace` flag. Are you doing minio in a different PR? are you not doing minio at all? i think it's better if we do that too. As a workaround we can install it in a separate hardocded namespace (mimir-minio?) ([see here](https://stackoverflow.com/a/71985378/5683949))

**Pull request merged**
