### PR TITLE
Handle TSDB native histogram validation errors as soft errors

### PR DESCRIPTION
**Pull request by krajorama**
#### What this PR does

Handle TSDB native histogram validation errors as soft errors.

#### Which issue(s) this PR fixes or relates to

Supersedes   #7736 

#### Checklist

- [X] Tests updated.
- N/A Documentation added.
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- N/A [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

### CODE REVIEW

**Comment by krajorama** [comment]
> Thank you. Code changes make sense to me. I'd prefer to have some tests for mapping of TSDB native histogram errors to correct errors from Mimir.

Added testcases for all scenarios.

**Review by pstibrany — APPROVED** [review]
Thank you very much!

**Review by pstibrany — APPROVED** [review]
Thank you!

**Comment by krajorama** [comment]
Additional metrics work in production: 
image

**Pull request merged**
