### PR TITLE
Enforce helm and jsonnet to match

### LINKED ISSUE #2591: Really enforce parity between Jsonnet and Helm
PR https://github.com/grafana/mimir/pull/2067 implemented checking the parity but hasn't turned on actual enforcement, that is CI does not fail due to the test.

We should fail CI when we're ready to enforce this.

### PR DESCRIPTION
**Pull request by krajorama**
#### What this PR does

Run the comparison and let github action fail instead of
capturing the error

#### Which issue(s) this PR fixes or relates to

Fixes #2591 

#### Checklist

- [x] Tests updated
- [N/A] Documentation added
- [N/A] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by Logiraptor — APPROVED** [review]
I am down to make this change, but I also wrote most of the kustomize config, so I would want others to approve as well before merging

**Review by dimitarvdimitrov — APPROVED** [review]
LGTM. My reasoning is that having this enforced is better than not having it enforced. If it's not enforced, we merge PRs that have this failing: we accumulate debt that we have to eventually fix. So far we've fixed it on the day, but it requires a context switch and is decoupled from the PR that caused the diff.

**Comment by pstibrany** [comment]
As someone not very familiar with Helm and only changing jsonnet most of the time, I'm not too happy about this change. I think it will slow us down, and it will be even more frustrating to contribute a PR than it already is, with all the lint checks we have (however useful they are). [It's not as bad as Thanos linters, but getting there fast 😄]

I realize it's going to happen (if we have jsonnet/helm consistency as a goal [*], it's definitely useful), but wanted to mention the cost of this change too.

**Comment by pracucci** [comment]
I think a good compromise is enforcing it, and then having Mimir Helm maintainers to jump on other people PRs to help adding Helm support whenever jsonnet changes, as a way to educate other people on how to contribute to Helm too.

**Comment by krajorama** [comment]
@Logiraptor For outside contributors this does not work as they will not see the difference. Our github token cannot open comments in their repo. That why I removed the whole commenting stuff in my original version. Is there a reason to do the comment now?

**Pull request merged**
