### PR TITLE
feat(mimirtool): add remote write command

### PR DESCRIPTION
**Pull request by fgouteroux**
Hello,

I would like to know if it is possible to integrate the `remote-write` command to push metrics directly from mimirtool.
```
mimirtool remote-write push /tmp/metrics --address http://localhost:8080
```

Currently I'm using a [custom tool](https://github.com/fgouteroux/prom) to do it.

If you agree I can add tests and review correctly my PR :-)

### CODE REVIEW

**Comment by dimitarvdimitrov** [comment]
I wonder if [Prometheus' `promtool`](https://github.com/prometheus/prometheus/blob/main/cmd/promtool/main.go) isn't a better fit for this functionality. Have you ran this by the Prometheus team?

**Comment by lamida** [comment]
The CHANGELOG has just been cut to prepare for the next Mimir release. Please rebase `main` and eventually move the CHANGELOG entry added / updated in this PR to the top of the CHANGELOG document. Thanks!

**Comment by fgouteroux** [comment]
> I wonder if [Prometheus' `promtool`](https://github.com/prometheus/prometheus/blob/main/cmd/promtool/main.go) isn't a better fit for this functionality. Have you ran this by the Prometheus team?

No, I didn't. But it could be too. The advantage here is to reuse the same logic to connect to mimir cluster with the tenant ID and the authentification.

**Comment by fgouteroux** [comment]
so is this PR could be accepted or should I give a try to promtool instead ?

**Comment by dimitarvdimitrov** [comment]
I think it's worth a try proposing this to the Prometheus project. The only difference with your proposal in this PR is the specific API key and tenant ID flags. I believe those can be set as arbitrary headers. I see the `promtool query` command doesn't have arbitrary headers, so that could be a blocker.

You can open an issue there and ask for feedback whether the team is open to hosting this.

My reasoning is that this is something that will be useful with any backend supporting the Prometheus remote-write, it's not Mimir-specific.

**Comment by fgouteroux** [comment]
I agree, this is the reason why I've created the [prom-push-cli](https://github.com/fgouteroux/prom-push-cli) tool to be agnostic of backend. (Initially it was created to be used with [thanos](https://github.com/thanos-io/thanos) before the migration to mimir last year).

So I will follow your advice and try to purpose this feature to the Prometheus project.

Thanks for your anwser.

**Comment by fgouteroux** [comment]
Trying the PR to Prometheus team inside promtool https://github.com/prometheus/prometheus/pull/12299

**Pull request closed without merging**
