### PR TITLE
Fix issue where autoscaling panels on dashboards can show multiple series for a single component

### PR DESCRIPTION
**Pull request by charleskorn**
#### What this PR does

This PR fixes an issue where the autoscaling panels on the dashboards in the mixin can show multiple series for a single component.

For example:

Screenshot 2023-08-22 at 4 06 11 pm

This can be caused by labels on either series in the query changing over time. (In the screenshot above, the KEDA operator was rescheduled twice, so the value of the `pod` label changed.)

#### Which issue(s) this PR fixes or relates to

(none)

#### Checklist

- [n/a] Tests updated
- [n/a] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by jhesketh — APPROVED** [review]
lgtm

**Review by dimitarvdimitrov — APPROVED** [review]
LGTM, thanks!

**Comment by dimitarvdimitrov** [comment]
I merged https://github.com/grafana/mimir/pull/5821 and realized it will conflict with your changes only after doing it. Sorry about that 😬

**Comment by charleskorn** [comment]
> I merged #5821 and realized it will conflict with your changes only after doing it. Sorry about that 😬

No worries 🙂

**Pull request merged**
