### PR TITLE
Support native histograms in ruler

### LINKED ISSUE #4155: ruler: Support native histograms in recording rules
#### Is your feature request related to a problem? Please describe.

Native histograms are not supported in recording rules yet. It will write a float value of 0 at the moment if the result was a histogram. Prometheus recently added support for float histograms and support for native histograms for recording rules, so it is time for us to add it in Mimir as well.

#### Describe the solution you'd like

Check the result of a recording rule result and store the histogram if the result was a histogram.

#### Additional context

https://github.com/prometheus/prometheus/pull/11838

### PR DESCRIPTION
**Pull request by codesome**
#### What this PR does

Makes ruler recognize native histograms coming out of rules.

#### Which issue(s) this PR fixes or relates to

Fixes #4155

#### Checklist

- [X] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by pstibrany — APPROVED** [review]
Code looks fine to me. Would you please add a changelog entry too (or make a note in existing one, if there is such entry for native histograms feature).

**Comment by codesome** [comment]
> Would you please add a changelog entry too

This PR is pointing to `sparsehistogram` branch. Do you suggest adding changelog entry to that? (Alternatively, should it point to main given query path is not merged yet?)

**Comment by pstibrany** [comment]
> This PR is pointing to `sparsehistogram` branch. Do you suggest adding changelog entry to that? (Alternatively, should it point to main given query path is not merged yet?)

Oh, sorry, I missed that! 🤦 Please ignore my feedback.

**Comment by codesome** [comment]
@pstibrany I added a new case as discussed offline and kind of revamped the unit test for it

**Review by krajorama — APPROVED** [review]

**Pull request merged**
