### PR TITLE
Streaming PromQL engine: extract linked list of series type

### PR DESCRIPTION
**Pull request by charleskorn**
#### What this PR does

This PR is a refactoring of the `Selector` type introduced in #7693, splitting its responsibilities into two more focused types to make its intent clearer.

It addresses https://github.com/grafana/mimir/pull/7693#discussion_r1556349944.

#### Which issue(s) this PR fixes or relates to

#7693

#### Checklist

- [x] Tests updated.
- [n/a] Documentation added.
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [n/a] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

### CODE REVIEW

**Comment by jhesketh** [comment]
Could you please add to the commit / PR description a bit of rationale for the change?

Otherwise it generally lgtm.

**Review by pracucci — APPROVED** [review]
Thanks for addressing my comment. LGTM!

**Comment by charleskorn** [comment]
> Could you please add to the commit / PR description a bit of rationale for the change?

@jhesketh how's this now?

**Comment by jhesketh** [comment]
> > Could you please add to the commit / PR description a bit of rationale for the change?
> 
> @jhesketh how's this now?

Yep, thanks :+1:

**Review by jhesketh — APPROVED** [review]

**Pull request merged**
