### PR TITLE
Track cortex_query_frontend_enqueue_duration_seconds metric even when query-scheduler is in use

### PR DESCRIPTION
**Pull request by pracucci**
#### What this PR does
I'm investigating some query performance and I noticed we don't have any metric to see how long it takes to enqueue requests in the query-frontend when query-scheduler is in use. Im this PR I propose to track `cortex_query_frontend_enqueue_duration_seconds` also when query-scheduler is in use, so that we can track the enqueuing latency end-to-end.

#### Which issue(s) this PR fixes or relates to

N/A

#### Checklist

- [x] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by dimitarvdimitrov — APPROVED** [review]
LGTM, thank you

**Review by charleskorn — APPROVED** [review]
LGTM.

Non-blocking suggestion: should we also split the metric by scheduler address, like we do for `cortex_query_frontend_workers_enqueued_requests_total`? This might be helpful if we're trying to track down if an issue is with an individual scheduler or all schedulers.

We typically only run two schedulers at a time, so I'm not expecting this to create a huge explosion in cardinality.

We could then also remove (or at least deprecate) `cortex_query_frontend_workers_enqueued_requests_total`, as it would be reporting the same information.

**Comment by pracucci** [comment]
> Non-blocking suggestion: should we also split the metric by scheduler address, like we do for cortex_query_frontend_workers_enqueued_requests_total? This might be helpful if we're trying to track down if an issue is with an individual scheduler or all schedulers.

Agree. See: https://github.com/grafana/mimir/pull/6120

**Comment by pracucci** [comment]
> We could then also remove (or at least deprecate) cortex_query_frontend_workers_enqueued_requests_total, as it would be reporting the same information.

Agree. See: https://github.com/grafana/mimir/pull/6121

**Pull request merged**
