### PR TITLE
Enable Nginx Proxy HTTP/1.1 in Mimir for Istio Envoy Sidecar Compatibility

### LINKED ISSUE #2845: Helm: nginx config not compatible with istio
#### Describe the bug
https://istio.io/latest/docs/ops/common-problems/network-issues/#envoy-won-t-connect-to-my-http-1-0-service

#### To Reproduce

1. Enable istio injection in your K8S namespace
1. Start Mimir from helm chart 3.1
2. Perform Operations(Read/Write/Others)

#### Expected behavior

Read/Write path works

#### Actual behavior

Getting HTTP status 426
#### Environment

- Infrastructure: latop with microk8s + istio
- Deployment tool: helm 3

#### Additional Context

Workaround helm value that should be enabled by default:
```
nginx:
  nginxConfig:
    httpSnippet: |
      proxy_http_version 1.1;
```

### PR DESCRIPTION
**Pull request by rafilkmp3**
## Description:

This PR is proposed to address issue #2845, which manifests as an HTTP 426 error when performing various operations with Mimir deployed in a Kubernetes namespace with Istio injection enabled.

### What this PR does

This PR sets the `proxy_http_version` directive to 1.1 in the Nginx configuration of Mimir. This change allows Mimir's Nginx to work harmoniously with the Istio Envoy sidecar. In our modern system architecture, the use of HTTP/1.1 is becoming increasingly crucial for the effective operation of service mesh architectures like Istio. 

### To Reproduce

The issue addressed by this PR can be reproduced using the following steps:

1. Enable Istio injection in your Kubernetes namespace.
2. Start Mimir from Helm chart 3.1.
3. Perform various operations (Read/Write/Others).

**Expected behavior**: The Read/Write path should work as intended.

**Actual behavior**: The server returns an HTTP 426 status error.

### Fixed issues

Fixes #2845

This PR resolves issue #2845 by enabling Nginx to use HTTP/1.1 as the default for proxying requests. This change helps improve the compatibility of Mimir with Istio sidecar Envoy.

### Checklist

- [x] Tests updated to validate the changes
- [x] Documentation updated to reflect new default configuration
- [x] `CHANGELOG.md` updated with a description of the changes, categorized under `[CHANGE]`

Please read the `CONTRIBUTING.md` guide before submitting and rebase your PR if it gets out of sync with the main branch. 

With this change, we're making a significant stride towards improving the interaction between Mimir, Nginx, and Istio. We believe it should be the default configuration, contributing to a more seamless experience for users in a modern system architecture.

### CODE REVIEW

**Review by dimitarvdimitrov — COMMENTED** [review]
Thanks for the contribution. This makes sense to me. I don't think forcing HTTP 1.1 is going to break existing users. But it's still a good idea to mention it as a CHANGE in the [helm chart changelog](https://github.com/grafana/mimir/blob/2917f0865603870d402b579593a1f122b9407f02/operations/helm/charts/mimir-distributed/CHANGELOG.md#L1-L0). 

Also, can you make the same change on the deprecated nginx deployment? https://github.com/rafilkmp3/mimir/blob/patch-1/operations/helm/charts/mimir-distributed/values.yaml#L2503

**Comment by Hronom** [comment]
Why not merge then?

**Comment by dimitarvdimitrov** [comment]
I think we can merge this fairly quickly. 
This is missing a changelog entry and also carrying out the change in the other nginx config (because the chart has two in parallel at this point).

@rafilkmp3 are you still able to carry out these changes?

**Comment by ceastman-r7** [comment]
@rafilkmp3 @dimitarvdimitrov Any update on this? We are waiting on this to be merged.

**Comment by dimitarvdimitrov** [comment]
@ceastman-r7 I updated the PR. I have one more question before I can merge this:

In the linked issue you mentioned that you might have to add the same to the location stanzas. Do you remember if this is required or the changes in this PR (only in the `http` stanza) are sufficient?

**Comment by ceastman-r7** [comment]
@dimitarvdimitrov I just tried the workaround: and it seemed to fix it, so i dont think the location stanzas need updating

gateway:
  enabledNonEnterprise: true
  nginx:
    config:
      httpSnippet: |
        proxy_http_version 1.1;

**Comment by dimitarvdimitrov** [comment]
thank you!

**Comment by dimitarvdimitrov** [comment]
thank you for the help @ceastman-r7 and @rafilkmp3. This will be included in mimir-distributed 5.3.0

**Review by dimitarvdimitrov — APPROVED** [review]

**Pull request merged**
