### PR TITLE
Docs: Fix broken link and align text

### PR DESCRIPTION
**Pull request by osg-grafana**
Fix https://github.com/grafana/mimir/issues/5789 in the `2.9.x` release.

### CODE REVIEW

**Review by jdbaldry — CHANGES_REQUESTED** [review]
In this target branch (release-2.9), the tutorial is still in the old directory (https://github.com/grafana/mimir/tree/release-2.9/docs/sources/mimir/tutorials/play-with-grafana-mimir).

**Comment by osg-grafana** [comment]
Per a conversation with @krajorama, we are telling them to clone the repo and that defaults to `main`.

**Comment by krajorama** [comment]
We could potentially tell the reader to check out the release branch, but I'm not sure that makes much sense.

**Comment by jdbaldry** [comment]
I see that makes sense

**Review by jdbaldry — APPROVED** [review]
Since this tutorial encourages users to use work from the `main` branch, these updated links make sense because those files have moved in that branch.

**Pull request merged**
