### PR TITLE
Update link to helm chart documentation

### PR DESCRIPTION
**Pull request by pr00se**
#### What this PR does

Mimir helm documentation has moved, so link to its new home

#### Which issue(s) this PR fixes or relates to

Fixes #<issue number>

#### Checklist

- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by 56quarters — APPROVED** [review]
LGTM

**Review by osg-grafana — CHANGES_REQUESTED** [review]
We need to correct "Getting" to "Get" because we are using imperatives for that guide across all documentation.

**Comment by pr00se** [comment]
Corrected the verbs in the text, but in the link itself using `get` vs `getting` leads to a 404. Is that something I should fix as part of this, or is that documentation moving soon anyway?

**Review by pracucci — APPROVED** [review]

**Comment by osg-grafana** [comment]
> @osg-grafana Corrected the verbs in the text, but in the link itself using `get` vs `getting` leads to a 404. Is that something I should fix as part of this, or is that documentation moving soon anyway?

Helm chart documentation is split out in `main` into subdirs for `mimir` and `helm-charts`.

**Review by osg-grafana — APPROVED** [review]
Going to fix this now and fix it again after the Helm chart documentation is launched.

**Comment by osg-grafana** [comment]
> Going to fix this now and fix it again after the Helm chart documentation is launched.

This is a fix for `latest` and a change is coming in `next`, so merging this now for `latest`.

**Pull request merged**
