### PR TITLE
[release-2.10] store-gateway: fix loading of series with chunks in multiple segment files

### PR DESCRIPTION
**Pull request by grafanabot**
Backport 85be770d67a332d4f5813d846a4ad785e1d570ba from #5875

### CODE REVIEW

**Review by dimitarvdimitrov — APPROVED** [review]

**Review by pstibrany — APPROVED** [review]

**Comment by colega** [comment]
Just to be clear, this bugfix belongs to an experimental feature that was included in rc.0?

**Comment by pstibrany** [comment]
> Just to be clear, this bugfix belongs to an experimental feature that was included in rc.0?

My understanding is that bug was introduced during the REMOVAL of the experimental feature.

**Comment by pracucci** [comment]
> Just to be clear, this bugfix belongs to an experimental feature that was included in rc.0?

No. It's about the normal store-gateway usage.

**Comment by colega** [comment]
Then this should be mentioned in the CHANGELOG, right?

**Comment by colega** [comment]
I think the changelog entry should belong to rc.1. 

I can later collapse it into the final release changelog.

**Comment by dimitarvdimitrov** [comment]
the removal wasn't part of a named release, so I added the PR number to changelog entry of the removal PR. Is that ok?

**Comment by dimitarvdimitrov** [comment]
ok i can add a new entry under rc1

**Review by colega — APPROVED** [review]

**Pull request merged**
