### PR TITLE
Helm: version of Mimir and GEM documenation links is now parametric

### PR DESCRIPTION
**Pull request by krajorama**
#### What this PR does

Instead of heaving to sed replace a bunch of links, make it parametric. Later when tech writer team introduces relref support between projects, this should be taken into account.

Bonus: fix link in vault integration doc.

#### Which issue(s) this PR fixes or relates to

N/A internal improvement

#### Checklist

- N/A Tests updated
- [x] Documentation added
- N/A `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by osg-grafana — APPROVED** [review]

**Review by dimitarvdimitrov — APPROVED** [review]
Nice one. Should we also update the RELEASE.md for the helm chart?

**Comment by jdbaldry** [comment]
Links appear to work as intended.

Before we merge this, I think we will want to override the `mimir_docs_version` parameter in the website to `latest` so that readers aren't moved out of "latest" docs into "v2.7.x" docs any time they click a link.

I think it is probably fine for `mimir-distributed` docs to link into the "v2.7.x" docs. We will also want to update `make docs` to mount the docs in the expected locations for testing. Something like `make docs PROJECTS='mimir:v2.7.x helm-charts/mimir-distributed:v2.7.x'`. We can set it as the default in `docs/variables.mk`

**Comment by krajorama** [comment]
> Links appear to work as intended.
> 
> Before we merge this, I think we will want to override the `mimir_docs_version` parameter in the website to `latest` so that readers aren't moved out of "latest" docs into "v2.7.x" docs any time they click a link.

I think it's worse if someone is in latest Helm chart doc, clicks a link and goes to latest Mimir but latest Mimir is newer than the version in the Helm chart (this will happen since we release Mimir first). In this case the newer Mimir documentation might not be applicable to the Helm chart, thus causing confusion. So using latest is exactly what I'm trying to avoid here :)

> 
> I think it is probably fine for `mimir-distributed` docs to link into the "v2.7.x" docs. We will also want to update `make docs` to mount the docs in the expected locations for testing. Something like `make docs PROJECTS='mimir:v2.7.x helm-charts/mimir-distributed:v2.7.x'`. We can set it as the default in `docs/variables.mk`
> 
> WDYT?

**Comment by krajorama** [comment]
> Nice one. Should we also update the RELEASE.md for the helm chart?

I think I did

**Pull request merged**
