### PR TITLE
Update mimir-prometheus to 19bfb1e6e195

### PR DESCRIPTION
**Pull request by colega**
#### What this PR does

This updates mimir-prometheus, including the bugfix from Prometheus:

https://github.com/prometheus/prometheus/pull/10607

#### Which issue(s) this PR fixes or relates to

N/A

#### Checklist

- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by osg-grafana** [comment]
@colega any need for a doc review on any of these bits? If so, lemme know. :)

**Comment by colega** [comment]
@osg-grafana thanks, I think no docs change is needed. Plus this is blocked by https://github.com/grafana/mimir/pull/1695

**Comment by pracucci** [comment]
@colega I just merged #1695. Could you rebase, please? I would like to begin reviewing this PR too.

**Comment by colega** [comment]
Done, now it's definitely much easier.

**Review by pracucci — APPROVED** [review]
It basically only contains https://github.com/prometheus/prometheus/pull/10607 so LGTM!

**Comment by pstibrany** [comment]
This PR actually fixed https://github.com/grafana/mimir/issues/1537, and has been released as part of Mimir 2.1.0. CHANGELOG entry is missing.

**Pull request merged**
