### PR TITLE
Include rate of label queries on "Reads" dashboard

### LINKED ISSUE #3063: Add label queriers to reads dashboard headlines
#### Is your feature request related to a problem? Please describe.

Due to the implementation details of the Graphite queriers, they make label value requests to the Mimir API for reads. These requests aren't included in the reads dashboard.

#### Describe the solution you'd like

We should add a label request number to the top of the reads dashboard.

### PR DESCRIPTION
**Pull request by 56quarters**
Fixes #3063

Signed-off-by: Nick Pillitteri <nick.pillitteri@grafana.com>

#### Checklist

- [ ] Tests updated
- [ ] Documentation added
- [X] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by 56quarters** [comment]
Screenshot
Screenshot 2022-09-27 at 14-18-05 Mimir _ Reads - Dashboards - Dashboards - Grafana

**Review by replay — APPROVED** [review]
Nice, thx!

**Comment by colega** [comment]
I think that if we add the label queries, we should also add the `/series` queries, as those are the heavy ones that Grafana is doing today.

**Review by colega — APPROVED** [review]

**Comment by pracucci** [comment]
> I think that if we add the label queries, we should also add the `/series` queries, as those are the heavy ones that Grafana is doing today.

Agree! @56quarters could you do it in a follow up? 🙏

**Pull request merged**
