### PR TITLE
Increased default configuration for -server.grpc-max-recv-msg-size-bytes and -server.grpc-max-send-msg-size-bytes from 4MB to 100MB

### LINKED ISSUE #1570: Increase gRPC max recv/send message to 100MB
In Mimir, we increased the default gRPC **clients** max recv/send message to 100MB. However, the gRPC server max recv/send message is still configured to 4MB.

Shouldn't we increase the gRPC server defaults to 100MB too, in order to client settings effective?

In our jsonnet we set the following overrides to **server gRPC** max recv/send limit:
- query-frontend: recv 100MB (recv increased to 400MB when query-sharding is enabled)
- ingester: recv/send 10MB
- ruler: recv/send 10MB

### LINKED ISSUE #1878: metric query to mimir cause grpc size overlimit error
#### Describe the bug
Add mimir as a data source of grafana, and run query in explore. Some mstrics' query will report **"server_error: server error: 500"**.
And on mimir server node, we can see log as:
```
May 18 19:07:12 mimir mimir: level=warn ts=2022-05-18T11:07:12.83689764Z caller=grpc_logging.go:55 method=/frontend.Frontend/Process duration=441h3m9.605752893s err="rpc error: code = ResourceExhausted desc = grpc: received message larger than max (7649243 vs. 4194304)" msg=gRPC
May 18 19:07:12 mimir mimir: level=error ts=2022-05-18T11:07:12.837081632Z caller=retry.go:78 org_id=anonymous msg="error processing request" try=0 err="rpc error: code = ResourceExhausted desc = grpc: received message larger than max (7649243 vs. 4194304)"
May 18 19:07:12 mimir mimir: level=error ts=2022-05-18T11:07:12.837188926Z caller=frontend_processor.go:75 msg="error processing requests" address=127.0.0.1:9095 err="rpc error: code = ResourceExhausted desc = grpc: received message larger than max (7649243 vs. 4194304)"
May 18 19:07:13 mimir mimir: level=warn ts=2022-05-18T11:07:13.028012798Z caller=grpc_logging.go:55 method=/frontend.Frontend/Process duration=441h3m9.792330604s err="rpc error: code = ResourceExhausted desc = grpc: received message larger than max (7649242 vs. 4194304)" msg=gRPC
May 18 19:07:13 mimir mimir: level=error ts=2022-05-18T11:07:13.0280805Z caller=retry.go:78 org_id=anonymous msg="error processing request" try=1 err="rpc error: code = ResourceExhausted desc = grpc: received message larger than max (7649242 vs. 4194304)"
May 18 19:07:13 mimir mimir: level=error ts=2022-05-18T11:07:13.028170872Z caller=frontend_processor.go:75 msg="error processing requests" address=127.0.0.1:9095 err="rpc error: code = ResourceExhausted desc = grpc: received message larger than max (7649242 vs. 4194304)"
May 18 19:07:13 mimir mimir: level=warn ts=2022-05-18T11:07:13.322637909Z caller=grpc_logging.go:55 duration=408.469887ms method=/frontend.Frontend/Process err="rpc error: code = ResourceExhausted desc = grpc: received message larger than max (7649242 vs. 4194304)" msg=gRPC
May 18 19:07:13 mimir mimir: level=error ts=2022-05-18T11:07:13.32269374Z caller=retry.go:78 org_id=anonymous msg="error processing request" try=2 err="rpc error: code = ResourceExhausted desc = grpc: received message larger than max (7649242 vs. 4194304)"
May 18 19:07:13 mimir mimir: level=error ts=2022-05-18T11:07:13.323606439Z caller=frontend_processor.go:75 msg="error processing requests" address=127.0.0.1:9095 err="rpc error: code = ResourceExhausted desc = grpc: received message larger than max (7649242 vs. 4194304)"
May 18 19:07:13 mimir mimir: level=warn ts=2022-05-18T11:07:13.512183122Z caller=grpc_logging.go:55 method=/frontend.Frontend/Process duration=390.553217ms err="rpc error: code = ResourceExhausted desc = grpc: received message larger than max (7649242 vs. 4194304)" msg=gRPC
May 18 19:07:13 mimir mimir: level=error ts=2022-05-18T11:07:13.51223363Z caller=retry.go:78 org_id=anonymous msg="error processing request" try=3 err="rpc error: code = ResourceExhausted desc = grpc: received message larger than max (7649242 vs. 4194304)"
May 18 19:07:13 mimir mimir: level=error ts=2022-05-18T11:07:13.512815383Z caller=frontend_processor.go:75 msg="error processing requests" address=127.0.0.1:9095 err="rpc error: code = ResourceExhausted desc = grpc: received message larger than max (7649242 vs. 4194304)"
May 18 19:07:13 mimir mimir: level=warn ts=2022-05-18T11:07:13.69717249Z caller=grpc_logging.go:55 method=/frontend.Frontend/Process duration=265.113238ms err="rpc error: code = ResourceExhausted desc = grpc: received message larger than max (7649242 vs. 4194304)" msg=gRPC
May 18 19:07:13 mimir mimir: level=error ts=2022-05-18T11:07:13.697231561Z caller=retry.go:78 org_id=anonymous msg="error processing request" try=4 err="rpc error: code = ResourceExhausted desc = grpc: received message larger than max (7649242 vs. 4194304)"
May 18 19:07:13 mimir mimir: level=warn ts=2022-05-18T11:07:13.697361309Z caller=logging.go:72 traceID=4b42dafadd3b75d1 msg="POST /prometheus/api/v1/query_range (500) 1.168035559s Response: \"rpc error: code = ResourceExhausted desc = grpc: received message larger than max (7649242 vs. 4194304)\\n\" ws: false; Accept-Encoding: gzip; Content-Length: 102; Content-Type: application/x-www-form-urlencoded; User-Agent: Grafana/8.4.7; "
May 18 19:07:13 mimir mimir: level=error ts=2022-05-18T11:07:13.697395448Z caller=frontend_processor.go:75 msg="error processing requests" address=127.0.0.1:9095 err="rpc error: code = ResourceExhausted desc = grpc: received message larger than max (7649242 vs. 4194304)"
```

It seem to be the problem of grpc packet size limit, but we didn't find any related configuration item from official doc. Is this a limitation managed by mimir, or grafana?

#### To Reproduce
See description above.

#### Expected behavior

any clue or instruction to tell user how to increase the limitation?

#### Environment

- Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
- Deployment tool: [e.g., helm, jsonnet]

### PR DESCRIPTION
**Pull request by pracucci**
#### What this PR does
As discussed in #1570, in this PR I propose to increase the default configuration for `-server.grpc-max-recv-msg-size-bytes` and `-server.grpc-max-send-msg-size-bytes` from 4MB to 100MB. Since we're increasing the default, I'm also removing the overrides from Jsonnet.

#### Which issue(s) this PR fixes or relates to

Fixes #1570
Fixes #1878

#### Checklist

- [ ] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by treid314 — APPROVED** [review]
LGTM, I can not tell you how many times I've had to increase this!

**Review by johannaratliff — APPROVED** [review]
:shipit:

**Comment by pracucci** [comment]
_Merging, given it will offer a better 1st time experience. If people has concerns, we can revisit it anytime._

**Comment by a2intl** [comment]
This wasn't big enough. We're still getting `[pod/mimir-querier-7447cdf86-mgcbc/querier] ts=2024-07-02T19:07:55.939892208Z caller=spanlogger.go:86 user=anonymous level=warn msg="failed to fetch label values" remote=10.85.163.185:9095 err="rpc error: code = ResourceExhausted desc = grpc: received message larger than max (220871382 vs. 104857600)"` messages. And now there's no way to set it larger.

**Pull request merged**
