### PR TITLE
query-frontend: stop using creation_grace_period to limit query length

### LINKED ISSUE #5445: max_query_into_future seems ignored
#### Describe the bug
Using `predict_linear()` function to get 1h metrics in the future (but any value after all) only returns back 10m in the future which match default `max_query_into_future: 10m`

By setting `max_query_into_future` to any value we still get 10m.

#### To Reproduce

1. Start Mimir 2.8
2. predict_linear(node_filesystem_avail_bytes{instance="your_instance"}[1h],3600)
3. When I ask Grafana `now-1h` to `now+1h` I only get 10m in the future

#### Expected behavior

When I use Prometheus I have metrics up to `1h` in the future. It's not the case when I query Mimir (same metrics, as Prometheus remote writes to Mimir)

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: Our internal tooling system.

#### Additional Context

image

image

### PR DESCRIPTION
**Pull request by dimitarvdimitrov**
#### What this PR does

Reviewing #7496 made me realize this.

#3144's reason for truncating queries is to not fill the scheduler queue with effectively useless queries. Some queries can legitimately be querying into the future without there being samples ingested for that time. For example `predict_linear` used on a longer term scale.

Since the impact of undoing this change in this PR is per-tenant I think it is reasonable - it will only impact the tenant sending the large queries. Perhaps worth noting that `-query-frontend.max-total-query-length` still applies.

#### Which issue(s) this PR fixes or relates to

Fixes #5445

#### Checklist

- [x] Tests updated.
- [x] Documentation added.
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [ ] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

### CODE REVIEW

**Comment by dimitarvdimitrov** [comment]
cc @hi-rustin @pracucci @colega since you were involved in the original work

**Comment by pracucci** [comment]
I'm not convinced removing it, sorry. IIRC, this protection was introduced after an incident and now we're removing that protection. Maybe we can convert it into a new dedicated limit, which is more generous (e.g. 1 day ahead is fine, 100 years ahead is not).

**Comment by dimitarvdimitrov** [comment]
> e.g. 1 day ahead is fine, 100 years ahead is not

we still have `max-total-query-length` which would reject a 100 year query. Why is a query into the future different from a query into the past? The former is much cheaper.

> IIRC, this protection was introduced after an incident and now we're removing that protection

I couldn't find the problem this caused. I think you just noticed it happening, but the actual problem was related to mmap and lazy loading.

**Review by colega — APPROVED** [review]
I agree with @dimitarvdimitrov's arguments: querying into the future should be cheaper than querying into the past, and still limited by the max query length.

**Review by pracucci — APPROVED** [review]
Ok, your arguments make sense.

**Pull request merged**
