### PR TITLE
Don't allocate an extra pointer in `mimirpb.ReuseSlice()`

### PR DESCRIPTION
**Pull request by colega**
#### What this PR does

We can avoid allocating an extra pointer just to put something into a pool if we store the pointer we got from the first pool in a second pool. Used the implementation of a pool from Prometheus for this.

```
goos: linux
goarch: amd64
pkg: github.com/grafana/mimir/pkg/util/push
cpu: 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz
               │   old.txt   │            new.txt            │
               │   sec/op    │   sec/op     vs base          │
PushHandler-16   1.635µ ± 8%   1.608µ ± 4%  ~ (p=0.289 n=10)

               │  old.txt   │              new.txt              │
               │    B/op    │    B/op     vs base               │
PushHandler-16   659.0 ± 0%   633.0 ± 0%  -3.95% (p=0.000 n=10)

               │  old.txt   │              new.txt              │
               │ allocs/op  │ allocs/op   vs base               │
PushHandler-16   17.00 ± 0%   16.00 ± 0%  -5.88% (p=0.000 n=10)
```

#### Which issue(s) this PR fixes or relates to

None, was just passing by.

#### Checklist

- [x] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by colega** [comment]
Also fixed the `BenchmarkPushHandler` which was not parsing the request at all, and after that it shows that one allocation saved. The cpu time difference gets diluted by the amount of time spent on the rest of the things.

```
$ benchstat old.txt new.txt
goos: linux
goarch: amd64
pkg: github.com/grafana/mimir/pkg/util/push
cpu: 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz
               │   old.txt   │            new.txt            │
               │   sec/op    │   sec/op     vs base          │
PushHandler-16   1.552µ ± 5%   1.496µ ± 5%  ~ (p=0.072 n=10)

               │  old.txt   │              new.txt              │
               │    B/op    │    B/op     vs base               │
PushHandler-16   658.0 ± 0%   634.0 ± 1%  -3.65% (p=0.000 n=10)

               │  old.txt   │              new.txt              │
               │ allocs/op  │ allocs/op   vs base               │
PushHandler-16   17.00 ± 0%   16.00 ± 0%  -5.88% (p=0.000 n=10)
```

**Comment by colega** [comment]
Lets wait until https://github.com/prometheus/prometheus/pull/12189 lands and use that instead of ad-hoc code.

**Comment by pracucci** [comment]
> Lets wait until [prometheus/prometheus#12189](https://github.com/prometheus/prometheus/pull/12189) lands and use that instead of ad-hoc code.

I looked at it, and I love it. Smart approach! Looking forward to get that PR merged and then used here.

**Comment by colega** [comment]
I rebased the branch using zeropool and updated the PR description, @pracucci PTAL.

**Comment by lamida** [comment]
The CHANGELOG has just been cut to prepare for the next Mimir release. Please rebase `main` and eventually move the CHANGELOG entry added / updated in this PR to the top of the CHANGELOG document. Thanks!

**Review by pracucci — APPROVED** [review]
LGTM!

**Comment by colega** [comment]
There's no changelog entry for this (it's a minor implementation change, I don't think it's worth it) so going to merge it once the CI passes.

**Pull request merged**
