### PR TITLE
Add logs cluster label override to helm chart

### LINKED ISSUE #7412: Logs cluster label cannot be customized in helm chart
#### Describe the bug
The mimir helm chart templates for metamonitoring logs uses `"mimir.clusterName"` for the `cluster` label which resolves to the `.Release.name` value in non-GEM installs afaict and thus the `cluster` label cannot be configured it appears.

Looks like this same issue used to affect metrics per #2084 (and https://github.com/grafana/helm-charts/issues/1387) and was resolved by adding `metaMonitoring.serviceMonitor.clusterLabel` in `values.yaml` and using it in the `ServiceMonitor` templates per #2125 and #4126.

#### To Reproduce

1. Write a helm chart values config with meta monitoring enabled
2. Include metrics and logs for comparison
3. Specify `metaMonitoring.serviceMonitor.clusterLabel` with a name different from name to be used in the helm release install, e.g. `"my-mimir-cluster"`
4. Install mimir via helm with a release name different from the `clusterLabel`, e.g. `my-mimir-helm-release`

```yaml
# ... other mimir helm chart config

metaMonitoring:
  serviceMonitor:
    enabled: true
    clusterLabel: "my-mimir-cluster"
  grafanaAgent:
    enabled: true
    installOperator: true
    logs:
      remote:
        url: "http://my-loki:3100/loki/api/v1/push"
```

```shell
helm -n my-mimir-namespace install my-mimir-helm-release grafana/mimir-distributed
```

5. Observe metrics are labeled with `cluster="my-mimir-cluster"` while logs are labeled with `cluster="my-mimir-helm-release"`

#### Expected behavior

Either the helm innstall also uses the `metaMonitoring.serviceMonitor.clusterLabel` for the cluster label on logging in addition to metrics or the `values.yaml` provides another mechanism for customizing the `cluster` label on logs similar to `serviceMonitor`.

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: helm

### PR DESCRIPTION
**Pull request by ian-lmcb**
#### What this PR does

Provide helm chart configuration point for overriding the `cluster` label used for Loki logs in the mimir metamonitoring configuration.

Adds `clusterLabel` to `metaMonitoring.grafanaAgent.logs` in `values.yaml` to allow overriding the cluster label for non-GEM configurations.

Previously the label was fixed to use `replacement: {{ include "mimir.clusterName" $ }}`. This PR changes the replacement to `replacement: "{{ .logs.clusterLabel | default (include "mimir.clusterName" $) }}"` which is the same as is done for ServiceMonitors, e.g. in the [KSM servmon template](https://github.com/grafana/mimir/blob/dcce59d4159931601f502e1780e83344e7736080/operations/helm/charts/mimir-distributed/templates/metamonitoring/kube-state-metrics-servmon.yaml#L32).

#### Which issue(s) this PR fixes or relates to

Fixes #7412

#### Checklist

- [x] Tests updated.
- [ ] ~Documentation added.~
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [ ] ~[`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.~

### CODE REVIEW

**Review by dimitarvdimitrov — APPROVED** [review]
LGTM, thank you for the change! I think we don't have to put this under `podLogs` because the `logs` sections is already somewhat specific to the `PodLogs` and `LogsInstance` resources

**Comment by dimitarvdimitrov** [comment]
Do you mind adding an `ENHANCEMENT` changelog entry in [operations/helm/charts/mimir-distributed/CHANGELOG.md](https://github.com/grafana/mimir/blob/5905fbea1a9451c6d53929e1d3d6b3c52ab280c3/operations/helm/charts/mimir-distributed/CHANGELOG.md)? I think we can merge after that

**Comment by ian-lmcb** [comment]
@dimitarvdimitrov sorry for the delay. I've added the `ENHANCEMENT` line. Let me know if there's anything else to do before merging

**Comment by ian-lmcb** [comment]
@dimitarvdimitrov oops! I just noticed I forgot to rebase on latest main and the enchancement line got merged into the 5.3.0 section. How do we fix?

**Pull request merged**
