### PR TITLE
Read users from tenant.index.json

### LINKED ISSUE #91: Allow to configure bucket caching for compactor
**Is your feature request related to a problem? Please describe.**
We have a Cortex cluster with a large number of tenants (tens of thousands). Discovering tenants in the bucket is very slow. The bucket listing is done by every compactor but we could reduce the load on the bucket configuring bucket caching for the compactor as well.

**Describe the solution you'd like**
Bucket caching for the compactor was not allowed because it's generally not safe, but there are few operations (like tenants discovery) for which it's expected to be safe, and I believe we should do it.

Submitted by: pracucci
Cortex Issue Number: 4047

### PR DESCRIPTION
**Pull request by vporoshok**
Signed-off-by: Bastrykov Evgeniy <evgeny.bastrykov@flant.com>

#### What this PR does

Minimization of top-level bucket listings (bad performance on CEPH) by using tenant.index.json file with list of users.

#### Which issue(s) this PR fixes or relates to

Fixes #91

#### Checklist

- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by vporoshok** [comment]
We use this patch with separated cron-job on bash to update file `tenant.index.json`. If changes are affordable let's discuss about how to implement updating this file in go-code.

**Comment by pracucci** [comment]
Thanks for opening this PR! I'm happy to consider adding a bucket index at root level, to index tenants, but I would start with a design doc first.

From an architectural perspective, I don't think we should assume there's a separate cron-job updating the root level bucket index, so updating it should be part of compactor duties. However, is it really different than adding memcached metadata support to compactor? I'm dubious about this approach because I've the feeling just adding metadata caching could solve your use case.

> Minimization of top-level bucket listings (bad performance on CEPH) by using tenant.index.json file with list of users.

Are you trying to reduce the number of top-level bucket listing done by compactor or any other Mimir component (e.g. store-gateway)? Excluding compactor, other components interacting with the bucket already support the metadata cache so you should get the exact same just configuring it.

> Fixes https://github.com/grafana/mimir/issues/91

The issue #91 describes something slightly different. It's about adding memcached metadata support to compactor. This PR may be considered as an alternative way of achieving #91, but just for the tenants listing. Metadata caching covers more bucket operations.

**Comment by vporoshok** [comment]
Thank you for detailed response.

Of course, we understudy that a separate cron-job isn’t a good solution. Because of this, we are started discussion, for finding right place for this job.

We made simple cron-job for fast checking our solution. Although compactor make not only list queries, but we have achieved a strong reduction in the load of Ceph by added tenant.index.json.

Does this solution eligible? Design is pretty close to bucket-index.json. If this changes acceptable, please help me with implementation. How to chose compactor from ring which will response for update this index?

**Comment by pracucci** [comment]
> Does this solution eligible?

I would start from memcached metadata caching first. I think you would get the same practical benefit, while better fitting in the Mimir design (given we already have metadata caching support for all components, except compactor).

However, to better undestand your use case, I think this question is this unanswered:

- Are you trying to reduce the number of top-level bucket listing done by compactor or any other Mimir component (e.g. store-gateway)? 
- Have you already configured memcached metadata cache for other components?

**Comment by pracucci** [comment]
I'm going to close this stale PR. We can get back to this anytime, but I would like to better understand the setup first (e.g. answering the questions in the previous comment).

**Pull request closed without merging**
