### PR TITLE
Fix aliases for http reference docs

### PR DESCRIPTION
**Pull request by colega**
#### What this PR does

Seems that it should start with /docs/

#### Which issue(s) this PR fixes or relates to

Ref: https://github.com/grafana/mimir/pull/4328

#### Checklist

- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by colega** [comment]
@osg-grafana trying to fix https://grafana.com/docs/mimir/latest/operators-guide/reference-http-api which doesn't work anymore, am I doing it right?

**Review by jdbaldry — CHANGES_REQUESTED** [review]
Unless we are going to change the version on old branches, we need this to be a relative alias.

Otherwise, old versions can "steal" a redirect from latest docs.

**Comment by colega** [comment]
I suspected that, @jdbaldry thank you for the review. Fixed alias to be relative, tested locally.

**Review by jdbaldry — APPROVED** [review]

**Review by osg-grafana — APPROVED** [review]
Thank you!

**Pull request merged**
