### PR TITLE
Prometheus: Add doc for starting Prometheus from scratch

### PR DESCRIPTION
**Pull request by bohandley**
#### What this PR does
Hello all! This is a tutorial for creating a Go app with Prometheus, creating custom metrics, using the Grafana Agent to deliver those metrics to Grafana Cloud, and visualizing the metrics. This is a first draft and will need images. 

Next steps/questions:

1. Is this the right place for this tutorial?
2. Where do I load images to access them in this doc?
3. Add images for creating visualizations in Grafana
4. Add steps to choose the appropriate functions and options in Grafana for the custom metrics.

#### Which issue(s) this PR fixes or relates to

Fixes https://github.com/grafana/technical-documentation/issues/557

#### Checklist

- [x] Documentation added

### CODE REVIEW

**Comment by osg-grafana** [comment]
(Removed myself because I am in `docs-metrics`.)

**Comment by 56quarters** [comment]
The CHANGELOG has just been cut to prepare for the next Mimir release. Please rebase `main` and eventually move the CHANGELOG entry added / updated in this PR to the top of the CHANGELOG document. Thanks!

**Comment by osg-grafana** [comment]
There is a new technical writer starting on the 28th of February who will be working in the area that is this guide. Unassigned myself, given that new context.

**Comment by osg-grafana** [comment]
It is unlikely that this will land in Mimir when it is published. Therefore, moving to `technical-documentation` repo.

**Comment by osg-grafana** [comment]
It is unlikely that this will land in Mimir when it is published. Therefore, moving to `technical-documentation` repo.

**Comment by pracucci** [comment]
@osg-grafana What's up with this PR? Is there any plan to move forward? Otherwise we may close it for now.

**Pull request closed without merging**
