### PR TITLE
query-tee: add equivalent errors for string expression for range queries

### PR DESCRIPTION
**Pull request by charleskorn**
#### What this PR does

This PR builds on https://github.com/grafana/mimir/pull/9143 to add another class of equivalent errors.

#### Which issue(s) this PR fixes or relates to

https://github.com/grafana/mimir/pull/9143

#### Checklist

- [n/a] Tests updated.
- [n/a] Documentation added.
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [n/a] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

### CODE REVIEW

**Review by jhesketh — COMMENTED** [review]
Could we also get this added to the list of tests?

**Comment by charleskorn** [comment]
> Could we also get this added to the list of tests?

My intention is that we'll add more and more of these equivalence classes over time, most of which will be simple patterns like these. I don't think it's worth adding more test cases for these, provided the general functionality of error equivalence is tested, but open to other opinions.

**Review by jhesketh — APPROVED** [review]
Okay, I'm not blocking on it, but maybe it's worth having a more generic test that loads each errorEquivalenceClasses pair, extracts the matching string and checks if it outputs the correct result (if that makes sense)

**Comment by charleskorn** [comment]
> Okay, I'm not blocking on it, but maybe it's worth having a more generic test that loads each errorEquivalenceClasses pair, extracts the matching string and checks if it outputs the correct result (if that makes sense)

This would be difficult to do as each pattern is a regex, not a string (although some of the patterns are just simple matches).

**Pull request merged**
