### PR TITLE
Use `DeletePartialMatch()`

### LINKED ISSUE #1764: Use the new Prometheus client's DeletePartialMatch()
Prometheus client introduced `MetricVec.DeletePartialMatch()` in https://github.com/prometheus/client_golang/pull/1013. This originates from an old standing request we had when we worked on https://github.com/cortexproject/cortex/pull/3784 and follow up PRs. I think we can now remove our `DeleteMatchingLabels()` utility and leverage on the new built-in `DeletePartialMatch()`.

### PR DESCRIPTION
**Pull request by LeviHarrison**
#### What this PR does

Switches from Mimir's own `DeleteMatchingLabels()` to client_golang's new `DeletePartialMatch()`.

#### Which issue(s) this PR fixes or relates to

Fixes #1764

#### Checklist

- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by pracucci — APPROVED** [review]
Thanks for working on this! This PR brings in quite a lot of changes to vendored libraries. Some notes:
- `github.com/prometheus/client_golang`: I checked the [changelog](https://github.com/prometheus/client_golang/releases/tag/v1.13.0) and LGTM. I've also reviewed the [PR introducing the `DeletePartialMatch()`](https://github.com/prometheus/client_golang/pull/1013) function and LGTM. The biggest changes are related to the Go collector and come from [this PR](https://github.com/prometheus/client_golang/pull/1102).
- `github.com/prometheus/common`: change to OAuth2 roundtripper, LGTM
- `github.com/prometheus/procfs`: I haven't checked changes, shouldn't really affect Mimir
- `google.golang.org/protobuf`: checked the [changelog](https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.28.1), LGTM


_Given we're not in a hurry, and given the Prometheus go client 1.13.0 has been released 3 days, we may wait a bit before merging or wait until another maintainer does a review on the changes we're vendoring._

**Comment by pracucci** [comment]
@LeviHarrison We merged some of these vendor updates as part of https://github.com/grafana/mimir/pull/2758. Can you rebase, please? Then I will merge this PR too. Thanks1

**Comment by LeviHarrison** [comment]
Rebased 👍🏻

**Comment by pracucci** [comment]
Thanks!

**Pull request merged**
