### PR TITLE
Rename DirectlyUnmarshalledByteSlice to YoloByteSlice.

### PR DESCRIPTION
**Pull request by charleskorn**
#### What this PR does

Follow up to feedback on https://github.com/grafana/mimir/pull/4625 received after merging.

#### Which issue(s) this PR fixes or relates to

#4625

#### Checklist

- [n/a] Tests updated
- [n/a] Documentation added
- [n/a] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by pracucci — APPROVED** [review]

**Comment by colega** [comment]
Late feedback to a late feedback, but IMO we should rename it to `UnsafeByteSlice`, as some time ago we started an effort removing the `YOLO` references from the code since they're not very descriptive.

**Comment by charleskorn** [comment]
> Late feedback to a late feedback, but IMO we should rename it to `UnsafeByteSlice`, as some time ago we started an effort removing the `YOLO` references from the code since they're not very descriptive.

I don't want to use the prefix "unsafe" as there's nothing unsafe about this (at least not with the current implementation of the gRPC library) - is there another convention that we could follow here?

**Comment by charleskorn** [comment]
Yeah I don't love the YOLO prefix either, but I thought I was following the convention for what that meant :) 

I don't believe this is unsafe to retain at the moment. There are two risks that I see with using this type:
- future changes to the gRPC library which result in the underlying buffer being reused before we've read the chunk
- unnecessarily keeping the underlying buffer alive when we're only interested in a small portion of it, increasing memory utilisation

Do we have a convention for naming things like this? If not, happy to use unsafe, but we would be broadening the meaning associated with unsafe to include "things that might be unsafe in the future if something changes but are currently perfectly safe".

**Comment by charleskorn** [comment]
Right, makes sense. I've opened #4676 to rename it.

**Pull request merged**
