### PR TITLE
Querier scheduler-processor: Move header manipulation out of backoff loop.

### PR DESCRIPTION
**Pull request by seizethedave**
#### What this PR does

This PR fixes a drive-by bug I noticed in the scheduler processor where if we're to stream the response but the first attempt fails, the second attempt in the backoff loop would no longer see it as a streaming response.

#### Checklist

- [x] Tests updated.
- [ ] Documentation added.
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [ ] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

### CODE REVIEW

**Comment by seizethedave** [comment]
I am keen to add a test for this, but it was not readily apparent how to do that. I'm open to suggestions!

**Review by flxbk — APPROVED** [review]
Thank you, LGTM.

**Review by dimitarvdimitrov — COMMENTED** [review]
I think it would be nice to add a test if it's not too time-consuming. I think this would be the extention place https://github.com/grafana/mimir/blob/9fccbacdabdd236cb7ff97cf154643b409078178/pkg/querier/worker/scheduler_processor_test.go#L356-L421

would need to make the frontend fail receiving some part of the request (`frontend.queryResultStreamErrorAfter = X`), but then succeed on a retry. I think this might need some changes on `frontendForQuerierMockServer` to allow this flexibility

**Comment by seizethedave** [comment]
Hah. Finally I realized that it's not easy to signal an error from a mocked stream server after the Nth send, because there's a layer of buffering in grpc.Server. A server may return an error, but the client may continue successfully writing a number of further stream messages without realizing anything is up. So I mocked out the entire `streamResponse` function that embodies all of that stream interaction.

Along those lines, is there a bug lurking in `streamResponse` where it doesn't verify that the frontend has received all of the chunks? It looks like after the initial metadata is sent, the frontend server could die completely and `streamResponse` would just say [all good](https://github.com/grafana/mimir/blob/4e0bc85a0b54a0f03a82d2294c13545b518a5e89/pkg/querier/worker/scheduler_processor.go#L379-L381). Something to think about- again, I don't know much about what's going on in this code. :)

**Review by dimitarvdimitrov — APPROVED** [review]
your changes LGTM

> Along those lines, is there a bug lurking in `streamResponse` where it doesn't verify that the frontend has received all of the chunks? It looks like after the initial metadata is sent, the frontend server could die completely and `streamResponse` would just say [all good](https://github.com/grafana/mimir/blob/4e0bc85a0b54a0f03a82d2294c13545b518a5e89/pkg/querier/worker/scheduler_processor.go#L379-L381). Something to think about- again, I don't know much about what's going on in this code. :)

I think we should manage retries and backoff separately for both the streaming and non-streaming code. _This_ PR along with the peculiarity you pointed to both arise from the fact that we use the same retry loop for different modes of response.

**Pull request merged**
