### PR TITLE
fix: go-kit/log-slog adapter fixes

### PR DESCRIPTION
**Pull request by tjhop**
Changes included:
- log/slog always includes timestamps by default; they are now included in the go-kit/log output. We make no attempts to adjust/remove any other timestamp keys (such as the often used `ts` kv pair in go-kit/log implementations).
- a new function to handle properly appending/nesting our kv pairs for the logger
- proper handling of nested grouping
- introduction of a `preformatted` field on the goKitHandler struct to cache previously added kv pairs containing log values. helpful to maintain the ordering of kv pairs added via multiple/nested/chained calls to a logger's `.With()` or `.WithGroup()` methods.
- WithGroup() now returns a new handler struct, as opposed to updating itself (as recommended by slog implementation docs).

Not addressed:
- tests still need to be updated. they currently use a mock logger, and the log lines have timestamps included. Since timestamps aren't deterministic, they're not easy to mock. I refrained from creating a wrapper interface to mock the time just for sake of testing; I used pattern matching with regexs when implementing slog tests for prometheus/common's `promslog` pkg.
- I haven't found a good way to (programmatically) address call depth when getting source caller info. Using a call depth of 6 (see code snippet) seems to properly unwind back to the originating `.Info()` etc method call, but I haven't checked other options.

Example output, after shimming the following logging calls into the existing handler test suite:

```go
gkadapterLogger := SlogFromGoKit(log.With(log.NewLogfmtLogger(os.Stderr), "caller", log.Caller(6)))
gkadapterLogger.Info("go-kit/log adapter output")
gkadapterLogger.WithGroup("g1").WithGroup("g2").Info("test1", "hello", "world")
gkadapterLogger.WithGroup("g1").With("hello", "world").Info("test2", "hello", "world")
gkadapterLogger.WithGroup("g1").With("hello", "world").WithGroup("g2").Info("test3", "hello", "world")
gkadapterLogger.With("hello", "world").With("hello", "world").Info("test4", "hello", "world")
// Output:
// level=info caller=slogadapter_test.go:26 time=2024-11-18T13:09:59.674350655-05:00 msg=test1 g1.g2.hello=world
// level=info caller=slogadapter_test.go:27 time=2024-11-18T13:09:59.674376383-05:00 msg=test2 g1.hello=world g1.hello=world
// level=info caller=slogadapter_test.go:28 time=2024-11-18T13:09:59.674392598-05:00 msg=test3 g1.hello=world g1.g2.hello=world
// level=info caller=slogadapter_test.go:29 time=2024-11-18T13:09:59.674419421-05:00 msg=test4 hello=world hello=world hello=world
```

#### Which issue(s) this PR fixes or relates to

Fixes #<issue number>

#### Checklist

- [ ] Tests updated.
- [ ] Documentation added.
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [ ] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

### CODE REVIEW

**Review by aknuds1 — APPROVED** [review]
LGTM, thanks

**Review by aknuds1 — CHANGES_REQUESTED** [review]
Can you fix failing tests?

**Review by dimitarvdimitrov — CHANGES_REQUESTED** [review]
can you explain why we need so many changes to the libraries
Screenshot 2024-11-19 at 11 18 30

Screenshot 2024-11-19 at 11 18 47


I'm especially concerned about the prometheus vendoring. Is this pulling in v3 changes?

**Comment by aknuds1** [comment]
@dimitarvdimitrov this is a PR against my [PR](https://github.com/grafana/mimir/pull/9844) :)

**Comment by tjhop** [comment]
@dimitarvdimitrov I rebased on @aknuds1's PR, the change set is now accurate (and much more reasonably sized :upside_down_face: )

**Comment by dimitarvdimitrov** [comment]
i'll leave the reviews to @aknuds1 since he's already involved

**Comment by tjhop** [comment]
Closing this PR in favor of library adoption in the parent PR

**Pull request closed without merging**
