### PR TITLE
Remove namespace from PodSecurityPolicy helm template

### PR DESCRIPTION
**Pull request by andrejvanderzee**
This PR fixes using the chart with kustomization terraform provider:

```╷
│ Error: github.com/kbst/terraform-provider-kustomize/kustomize.kustomizationResourceDiff: "policy/PodSecurityPolicy/perfana/mimir-distributed": is not namespace scoped but has metadata.namespace set
```

PodSecurityPolicies are not namespaced so the chart is indeed incorrect.

### CODE REVIEW

**Comment by dimitarvdimitrov** [comment]
Thanks for fixing this! Is this something that manifests only when using a kustomization terraform provider?

Regarding the failing CI checks:

* __helm-ci / conftest (pull_request)__ is failing because we check that all resources generated from the chart have a namespace. This check doesn't make sense in this case. We enforce this with rego policies. I will open a PR against your branch to correct this assumption in our rego policies.
* __ci / lint-helm (pull_request)__ is failing because we also render some manifests and commit them to the repo. This helps seeing what real changes something in the chart has. The CI is failing because the committed manifests are out of date. Can you run `make build-helm-tests` locally and commit what's changed?

**Comment by dimitarvdimitrov** [comment]
another note: that PSP is also wrong in that the containers and Pods from the chart don't comply to it :( I have an open PR https://github.com/grafana/mimir/pull/3007 to correct all of that.

**Comment by andrejvanderzee** [comment]
> Thanks for fixing this! Is this something that manifests only when using a kustomization terraform provider?

Yes `helm template` ignores the namespace apparently:
```helm template grafana --release-name grafana/mimir-distributed --namespace perfana --values values.yml --version 3.1.0```
No errors.

**Comment by dimitarvdimitrov** [comment]
I opened https://github.com/andrejvanderzee/mimir/pull/1 for the rego policies

**Comment by krajorama** [comment]
Hi, please run `make check-helm-tests` to refresh the golden records which currently fail in ci/lint-helm above^

**Comment by krajorama** [comment]
hi @andrejvanderzee  will you finalize this PR ? Seems like it needs a rebase and [changelog](https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/CHANGELOG.md) entry.

**Comment by replay** [comment]
The CHANGELOG has just been cut to prepare for the next Mimir release. Please rebase `main` and eventually move the CHANGELOG entry added / updated in this PR to the top of the CHANGELOG document. Thanks!

**Comment by pracucci** [comment]
> hi @andrejvanderzee will you finalize this PR ? Seems like it needs a rebase and [changelog](https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/CHANGELOG.md) entry.

@krajorama This PR looks stale. If it's something we want, maybe we could just take it over and make it through the finish line 🏁 ?

**Comment by krajorama** [comment]
superseded by #4164

**Pull request closed without merging**
