### PR TITLE
Improve 'Mimir / Compactor resources' and 'Mimir / Alertmanager resources' dashboards to work with read-write deployment mode

### PR DESCRIPTION
**Pull request by pracucci**
#### What this PR does
This PR is a follow up of #3504. Since compactor and alertmanager resources dashboard just focus on these respective components, we could query both `compactor` and `mimir-backend` (which is also what I proposed in the issue #3361). This is what I'm doing in this PR.

Now that I see it, I have mixed feelings. I fear it may be misleading showing `mimir-backend` resources in the "Compactor resources" dashboard when an operator may just expect to see the compacto resources.

**Draft** because I'm looking for feedback about ☝️ .

**Screenshot of microservices deployment:**
Screenshot 2022-11-23 at 18 54 20

**Screenshot of read-write deployment:**
Screenshot 2022-11-23 at 18 54 28

#### Which issue(s) this PR fixes or relates to

Part of #3361.

#### Checklist

- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by 56quarters** [comment]
> Now that I see it, I have mixed feelings. I fear it may be misleading showing `mimir-backend` resources in the "Compactor resources" dashboard when an operator may just expect to see the compacto resources.

I agree that it may be confusing but I don't think there is a good way to split out resources used by specifically compaction when it's running as part of `mimir-backend`. I think the least surprising thing here would be to generate a different set of resources dashboards specifically for read-write mode because of the way we're combining various components that would be separate in microservices mode. That's probably easier said than done.

**Comment by jhesketh** [comment]
Change lgtm, but I was thinking the same thing as @56quarters (while also reviewing the other related changes).

The other thing to consider is how many of these modes we are going to maintain the future. If we expect to only do one or another then forking the dashboards may not be a bad idea instead of maintaining a lot of conditional statements. I realise that is a discussion to come though.

**Comment by pracucci** [comment]
> I think the least surprising thing here would be to generate a different set of resources dashboards specifically for read-write mode because of the way we're combining various components that would be separate in microservices mode.

The whole goal of my work is to **not** generate specific dashboards. I want to do the best to use the same dashboards between microservices and read-write deployment mode.

**Comment by dimitarvdimitrov** [comment]
my two cents are that it's ok to have duplicating dashboards. Effectively alertmanager, compactor, ruler, and backend resources dashboards will show the same data when running read-write mode.

One other option is to have a single resources dashboard that has a dynamic dropdown with all the available components (discovered via a promql query). The user can select all or some of the components and the dashboard will repeat a panel row (CPU, memory, heap) for each component. I think we can tinker with variables in grafana and show extra disk or RSS panels for e.g. the store-gateway and the ingester.

**Comment by pracucci** [comment]
I'm closing this for now.

**Pull request closed without merging**
