### PR TITLE
[helm] Add startupProbes to all components

### PR DESCRIPTION
**Pull request by AlexLov**
#### What this PR does

Adds startupProbes to every component in helm chart where readinessProbe present.

When mimir-ingester and/or mimir-store-gateway overloaded and crashed or killed by OOMKiller, they require significant time on startup to process all WAL files or whatever they do, and this time usually why over the readinessProbe gives them so they are finishes in a kinda endless loop of starting up and got killed by kubernetes. In this case startupProbes should help them with recovery after outage by themselves.

I guess only ingester and store-gateway really need these probes, but I added it everywhere where readinessProbe present, just for consistency.

#### Checklist

- [ ] Tests updated.
- [ ] Documentation added.
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [ ] [`about-versioning.md`](/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

### CODE REVIEW

**Comment by AlexLov** [comment]
Oh, it seems it duplicates this PR #6738 in some way, but it looks stale.

**Comment by dimitarvdimitrov** [comment]
Thank you for opening the PR @AlexLov 

> this time usually why over the readinessProbe gives them so they are finishes in a kinda endless loop of starting up and got killed by kubernetes. In this case startupProbes should help them with recovery after outage by themselves.

can you help me understand why startup probes would help here? The kubernetes docs mention startup probes to replacements of liveness probes when the containers have a long startup time. But I don't see how they would help in preventing an endless OOM loop. Can you give a concrete example maybe?

**Comment by AlexLov** [comment]
No, it's not a replacement but addition. Generally speaking `startupProbe` is a little be more intelligent version of `initialDelaySeconds` parameter from `readinessProbe`

If we have a process that become ready anywhere in between 30 seconds and 30 minutes than pod will be killed and recreated by k8s if it couldn't report its readiness in 2-3+ minutes with default `readinessProbe` settings, and if the process needs to process some files on startup then it will start doing it from the beggining and here we have an endless restart loop.
To solve it we can increase initial delay for readinessProbe or increase amount of attempts it performs. In first case we hugely affect startup time in normal circumstances (imagine 30 minutes initial delay * 10 statefulset replicas == 5 hours just to restart them all), in later one we sacrifice response time from kubernetes to restart the pod when the process hangs during its operation.
So `startupProbe` solves this issue, it can wait longer on startup and hand out observation to `readinessProbe` as soon as it gets good response (no need to wait the whole initial delay time) without sacrificing fast k8s response from readinessProbe during normal operation.

**Comment by AlexLov** [comment]
Hey @dimitarvdimitrov,
Should I fix tests too by adding `startupProbe` to expected results? Or better to add condition so `startupProbe` so it won't be added by default to rendered yamls?

**Comment by dimitarvdimitrov** [comment]
> If we have a process that become ready anywhere in between 30 seconds and 30 minutes than pod will be killed and recreated by k8s if it couldn't report its readiness in 2-3+ minutes with default `readinessProbe` settings

Do you have some kubernetes docs to support this? I think kubernetes relies on liveness probes to delete pods. readiness probes only control whether the pod is listed in services' endpoints ([docs on Container v1](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#container-v1-core))

**Comment by AlexLov** [comment]
Ok, I might mixed liveness and readiness probes in my mind. I experienced this issue a half year ago so might forgot some details.

**Comment by dimitarvdimitrov** [comment]
ok, thanks for the discussion. Feel free to reopen if storatup probes are proven to help in some scenarios

**Comment by AlexLov** [comment]
So `startupProbe` is useful if there is `livenessProbe` configured. So why do you give an option to configure `livenessProbe` on all pods but reject to add option to configure `startupProbe`?

**Comment by dimitarvdimitrov** [comment]
Fair point, but liveness probes not set by default and I don't see the problem they're solving for Mimir. What do you solve with liveness probes for Mimir?

I'm more inclined to delete support for liveness probes than to add support for startup probes.

**Comment by AlexLov** [comment]
Oh, if you’re going to delete liveness probes than yes, it makes sense to decline this PR.

**Comment by dimitarvdimitrov** [comment]
There are no hard plans for either, but perhaps understanding the need for liveness probes would help me/us make a decision and eventually do one (accept your PR or delete liveness probes)

**Pull request closed without merging**
