### PR TITLE
Revert tutorial's common config usage

### PR DESCRIPTION
**Pull request by colega**
#### What this PR does

Tutorial can't use common config yet as it will be released in 2.3.
This reverts the common config usage, and I'll create an issue to bring it back after releasing 2.3. Edit: issue https://github.com/grafana/mimir/issues/2377

#### Which issue(s) this PR fixes or relates to

Fixes https://github.com/grafana/mimir/issues/2374

#### Checklist

- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by pracucci — COMMENTED** [review]
We also have an e2e test on the tutorial config. Shouldn't you update the e2e test too?

**Comment by colega** [comment]
The e2e test runs on the image from `main`, so _should_ work fine (it will actually override the specific yaml values by common cli flags).

I think we can leave it that way, wdyt?

**Comment by pracucci** [comment]
> The e2e test runs on the image from `main`, so _should_ work fine (it will actually override the specific yaml values by common cli flags).
> 
> I think we can leave it that way, wdyt?

With this PR the bucket names have changed. I think you need to update it in Minio initialisation in the e2e test.

**Review by pracucci — APPROVED** [review]
I'm approving cause the revert is fine. I still think you need to update the e2e test.

**Comment by pracucci** [comment]
> I'm approving cause the revert is fine. I still think you need to update the e2e test.

See changes you did here:
https://github.com/grafana/mimir/pull/2330/files#diff-da791319a110c642b310ebc4224d61d6c12d7933bde3d9c789a6d98721fe6299

**Comment by colega** [comment]
> With this PR the bucket names have changed. I think you need to update it in Minio initialisation in the e2e test.

The e2e is actually half-way testing the tutorial, as it doesn't really use the Minio from the tutorial.

I can revert the e2e test change, but it won't be _more correct_ or testing more things by doing that, because it would still override the YAML config by providing its own CLI flags and it instantiates its own Minio anyway.

If we want to test the tutorial properly, IMO, we should do the `docker-compose up` in the CI.

**Comment by colega** [comment]
Reverted in https://github.com/grafana/mimir/pull/2376/commits/bb0125e32a577215396932e3f81fcef73037e8cc

**Pull request merged**
