### PR TITLE
Fix mimir-write Kubernetes service to correctly balance route requests among mimir-write pods

### LINKED ISSUE #3804: Investigate increased latency when migrating write path from microservices to read-write mode
We've migrated a test Mimir cluster (with 8M active series) from microservices to read-write mode. At 17:30 UTC we switched the write traffic from `distributor` (microservices) to `mimir-write` (read-write) and at the same time we started experiencing an higher write latency. No other change was done at this time. The higher latency persists over time, so it's not temporarily.

The increased latency is measured in the distributor component (so distributor endpoint):

Screenshot 2022-12-22 at 12 19 17

No higher latency when measured in the ingester endpoint:

Screenshot 2022-12-22 at 12 19 22

### PR DESCRIPTION
**Pull request by pracucci**
#### What this PR does
See explanation in https://github.com/grafana/mimir/issues/3804#issuecomment-1371932856.

#### Which issue(s) this PR fixes or relates to

Fixes #3804

#### Checklist

- [ ] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by colega — APPROVED** [review]

**Comment by 56quarters** [comment]
Don't we also need a non-headless service for use with non-gRPC gateways (e.g. Nginx)?

**Comment by pracucci** [comment]
> Don't we also need a non-headless service for use with non-gRPC gateways (e.g. Nginx)?

I thought about it and I don't think so. Typically load balancer (e.g. nginx) can handle the case the configure address resolves to multiple addresses and then load balance across them (which is the actual purpose of a load balancer).

**Comment by sandeepsukhani** [comment]
I can't find much in the kubernetes docs, but we fixed this issue without making the service headless and just naming the port `grpclb`. Here is the PR https://github.com/grafana/loki/pull/4737/files#diff-ebb08a78f9fc27e80ef89a3994eb1618b1a379754da349899e298bf74228e970R21

The only relevant things I can find are:
* https://yidongnan.github.io/grpc-spring-boot-starter/en/kubernetes.html
* https://github.com/grpc/grpc/blob/master/doc/load-balancing.md

**Comment by pracucci** [comment]
Thanks @sandeepsukhani ! Making the K8S server headless is one part of the solution, but then you also need the gRPC client to periodically re-resolve the address. The trick we use is to enforce a relative short max connection age (2m) on the gRPC server side.

See https://github.com/grafana/mimir/issues/3804 for more details about what we do in Mimir.

**Pull request merged**
