### PR TITLE
Don't copy chunks when unmarshalling responses from store gateways or ingesters.

### PR DESCRIPTION
**Pull request by charleskorn**
#### What this PR does

This PR replaces protobuf's default unmarshalling behaviour when unmarshalling byte slices with an alternative implementation that does not copy the bytes from the underlying protobuf buffer, but instead retains a reference to a subslice of that buffer.

Based on a brief test in a test cell at Grafana Labs, peak heap utilisation for queriers is reduced by ~5-10%, with no significant change to CPU. (This change was deployed to queriers around 16:45 in the screenshots below.)

Screenshot 2023-03-30 at 5 05 49 pm

Screenshot 2023-03-30 at 5 14 34 pm

Given the low query throughput and uneven nature of the query pattern in this environment, I'd like to test this change further to confirm its impact before merging, but I'd like to get some feedback on the approach before I invest time into doing that.

#### Which issue(s) this PR fixes or relates to

(none)

#### Checklist

- [n/a] Tests updated
- [n/a] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by charleskorn** [comment]
> I don't remember if queriers may "release" chunks progressively or, in practice, chunks are released all at once. In the first case, this optimization may be potentially controversial, while in the latter case this optimization LGTM.

I believe the chunks are released all at once - for example, for queries that touch chunks in ingesters, the series set contains references to the chunks ([reference](https://github.com/grafana/mimir/blob/cb9ab74183d1833ab003e1b0a5693ab5f4e8edfd/pkg/querier/distributor_queryable.go#L141-L161)), and the series set is retained until the last chunk of the last series is read. The behaviour is the same for queries that touch chunks in store gateways.

**Comment by charleskorn** [comment]
I ran a second test today, this time using this change for queriers used for remote rule evaluation to create a more consistent test scenario.

Results (change deployed around 00:55):

Screenshot 2023-03-31 at 1 02 15 pm

_CPU, working set and heap usage per instance - each line represents one instance_

Screenshot 2023-03-31 at 1 02 53 pm

_Aggregate working set usage across all pods_

Screenshot 2023-03-31 at 1 03 04 pm

_Aggregate heap usage across all pods_

Notes: 
* CPU usage increased slightly, but this seems to be due to an increase in configuration API calls around the same time, rather than this change
* working set and heap are both reduced, with lower average consumption and fewer peaks, and the peaks that do occur are lower

**Comment by pracucci** [comment]
> CPU usage increased slightly, need to investigate further

Since we're not in a hurry to merge this PR, I suggest to investigate ☝️ first. Reason is that from a TCO perspective, CPU is more expensive than memory.

**Comment by charleskorn** [comment]
> > CPU usage increased slightly, need to investigate further
> 
> Since we're not in a hurry to merge this PR, I suggest to investigate ☝️ first. Reason is that from a TCO perspective, CPU is more expensive than memory.

I've done some further digging on this and I can't reproduce it: after redeploying this change, CPU usage is unchanged compared to the previous version. 

Profiles from the previous version and this change look as expected: reduced CPU time spent doing GC and copying bytes around, and no other substantial changes.

Looking back over a few days, with the previous version deployed, CPU usage varies up and down (possibly due to noisy neighbours on the same node), and the previous test's CPU utilisation wasn't out of the ordinary in comparison, so I'm comfortable proceeding with this.

**Pull request merged**
