### PR TITLE
Helm: bump version in CHANGELOG to signal start of release

### PR DESCRIPTION
**Pull request by krajorama**
#### What this PR does

We're adding commits on main, let's not mix up 3.1 future released and non
released stuff

#### Which issue(s) this PR fixes or relates to

N/A

#### Checklist

- [N/A] Tests updated
- [N/A] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by dimitarvdimitrov — APPROVED** [review]
I think we already cut the changelog for the non-helm changes in #2704. Should we update the release instructions to do the same for helm?

**Comment by dimitarvdimitrov** [comment]
I just merged a the query-scheduler PR, can you rebase?

**Comment by dimitarvdimitrov** [comment]
> I think we already cut the changelog for the non-helm changes in #2704. Should we update the release instructions to do the same for helm?

But we committed to having the two separate, so doesn't make much sense to couple them again in the changes' cutting. I retract my comment.

**Comment by krajorama** [comment]
> I just merged a the query-scheduler PR, can you rebase?

rebased

**Review by dimitarvdimitrov — APPROVED** [review]

**Pull request merged**
